export const dealers = [
  // ── Münsterland / Lüdinghausen Umgebung ──
  {
    id: 1,
    name: "Zweirad Hölscher",
    type: "Werkstatt",
    lat: 51.77,
    lng: 7.444,
    city: "Lüdinghausen",
  },
  {
    id: 2,
    name: "Motorrad Schrauber Lüdinghausen",
    type: "Werkstatt",
    lat: 51.7685,
    lng: 7.451,
    city: "Lüdinghausen",
  },
  {
    id: 3,
    name: "Fahrschule Lüdinghausen",
    type: "Fahrschule",
    lat: 51.771,
    lng: 7.4475,
    city: "Lüdinghausen",
  },
  {
    id: 4,
    name: "Motorrad Müller Senden",
    type: "Werkstatt",
    lat: 51.8558,
    lng: 7.4987,
    city: "Senden",
  },
  {
    id: 5,
    name: "Bike Corner Dülmen",
    type: "Werkstatt",
    lat: 51.831,
    lng: 7.281,
    city: "Dülmen",
  },
  {
    id: 6,
    name: "Fahrschule Senden",
    type: "Fahrschule",
    lat: 51.854,
    lng: 7.502,
    city: "Senden",
  },
  {
    id: 7,
    name: "Zweirad Selm",
    type: "Werkstatt",
    lat: 51.687,
    lng: 7.467,
    city: "Selm",
  },
  {
    id: 8,
    name: "Motorrad Zentrum Münster",
    type: "Werkstatt",
    lat: 51.9607,
    lng: 7.6261,
    city: "Münster",
  },
  {
    id: 9,
    name: "Harley-Davidson Münster",
    type: "Händler",
    lat: 51.9385,
    lng: 7.609,
    city: "Münster",
  },
  {
    id: 10,
    name: "Yamaha Center Münster",
    type: "Händler",
    lat: 51.951,
    lng: 7.635,
    city: "Münster",
  },
  {
    id: 11,
    name: "Fahrschule Münster Moto",
    type: "Fahrschule",
    lat: 51.962,
    lng: 7.6285,
    city: "Münster",
  },
  {
    id: 12,
    name: "Kawasaki Hamm",
    type: "Händler",
    lat: 51.6738,
    lng: 7.8159,
    city: "Hamm",
  },
  {
    id: 13,
    name: "Motorrad Werkstatt Hamm",
    type: "Werkstatt",
    lat: 51.68,
    lng: 7.82,
    city: "Hamm",
  },
  {
    id: 14,
    name: "Fahrschule Hamm",
    type: "Fahrschule",
    lat: 51.675,
    lng: 7.81,
    city: "Hamm",
  },
  {
    id: 15,
    name: "Honda Motorradzentrum Coesfeld",
    type: "Händler",
    lat: 51.9436,
    lng: 7.1676,
    city: "Coesfeld",
  },
  {
    id: 16,
    name: "Bike Service Nordkirchen",
    type: "Werkstatt",
    lat: 51.737,
    lng: 7.526,
    city: "Nordkirchen",
  },

  // ── NRW ──
  {
    id: 20,
    name: "Suzuki Essen",
    type: "Werkstatt",
    lat: 51.4556,
    lng: 7.0116,
    city: "Essen",
  },
  {
    id: 21,
    name: "Yamaha Düsseldorf",
    type: "Händler",
    lat: 51.2277,
    lng: 6.7735,
    city: "Düsseldorf",
  },
  {
    id: 22,
    name: "Motorrad Dortmund",
    type: "Werkstatt",
    lat: 51.5136,
    lng: 7.4653,
    city: "Dortmund",
  },
  {
    id: 23,
    name: "Honda Dortmund",
    type: "Händler",
    lat: 51.51,
    lng: 7.47,
    city: "Dortmund",
  },
  {
    id: 24,
    name: "Fahrschule Dortmund",
    type: "Fahrschule",
    lat: 51.515,
    lng: 7.46,
    city: "Dortmund",
  },
  {
    id: 25,
    name: "Fahrschule Köln",
    type: "Fahrschule",
    lat: 50.9365,
    lng: 6.9589,
    city: "Köln",
  },
  {
    id: 26,
    name: "Motorrad Köln",
    type: "Werkstatt",
    lat: 50.94,
    lng: 6.96,
    city: "Köln",
  },

  // ── Weitere Großstädte ──
  {
    id: 30,
    name: "Honda Hannover",
    type: "Werkstatt",
    lat: 52.3667,
    lng: 9.7165,
    city: "Hannover",
  },
  {
    id: 31,
    name: "Honda München",
    type: "Werkstatt",
    lat: 48.1351,
    lng: 11.582,
    city: "München",
  },
  {
    id: 32,
    name: "Harley-Davidson München",
    type: "Händler",
    lat: 48.1667,
    lng: 11.5833,
    city: "München",
  },
  {
    id: 33,
    name: "Fahrschule Nürnberg",
    type: "Fahrschule",
    lat: 49.4521,
    lng: 11.0767,
    city: "Nürnberg",
  },
  {
    id: 34,
    name: "Kawasaki Stuttgart",
    type: "Werkstatt",
    lat: 48.7758,
    lng: 9.1829,
    city: "Stuttgart",
  },
  {
    id: 35,
    name: "Yamaha Karlsruhe",
    type: "Händler",
    lat: 49.0134,
    lng: 8.4043,
    city: "Karlsruhe",
  },
  {
    id: 36,
    name: "Fahrschule Frankfurt",
    type: "Fahrschule",
    lat: 50.1109,
    lng: 8.6821,
    city: "Frankfurt",
  },
  {
    id: 37,
    name: "Suzuki Frankfurt",
    type: "Werkstatt",
    lat: 50.1109,
    lng: 8.7,
    city: "Frankfurt",
  },
  {
    id: 38,
    name: "Honda Berlin",
    type: "Werkstatt",
    lat: 52.52,
    lng: 13.405,
    city: "Berlin",
  },
  {
    id: 39,
    name: "Fahrschule Berlin",
    type: "Fahrschule",
    lat: 52.528,
    lng: 13.406,
    city: "Berlin",
  },
  {
    id: 40,
    name: "BMW Motorrad Berlin",
    type: "Händler",
    lat: 52.51,
    lng: 13.39,
    city: "Berlin",
  },
  {
    id: 41,
    name: "KTM Hamburg",
    type: "Händler",
    lat: 53.5511,
    lng: 9.9937,
    city: "Hamburg",
  },
  {
    id: 42,
    name: "Motorrad Werkstatt Hamburg",
    type: "Werkstatt",
    lat: 53.555,
    lng: 10.0,
    city: "Hamburg",
  },
  {
    id: 43,
    name: "Fahrschule Hamburg",
    type: "Fahrschule",
    lat: 53.553,
    lng: 9.995,
    city: "Hamburg",
  },
];

export function findNearby(lat, lng, radius = 50) {
  return dealers
    .filter((d) => distance(lat, lng, d.lat, d.lng) <= radius)
    .sort(
      (a, b) =>
        distance(lat, lng, a.lat, a.lng) - distance(lat, lng, b.lat, b.lng),
    );
}

function distance(lat1, lon1, lat2, lon2) {
  const R = 6371,
    dLat = ((lat2 - lat1) * Math.PI) / 180,
    dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}
