/**
 * ══════════════════════════════════════════════════════════════
 *  MOTOMATCH — gear.js  v4.0
 *  8 categories per style: helmet, jacket, gloves, boots,
 *  pants, kidneybelt, balaclava, backprotector
 * ══════════════════════════════════════════════════════════════
 */

/* ─── Universal categories (same across all styles) ─── */
const universalGear = {
  kidneybelt: [
    { name: "Büse Stream Nierengurt",     type: "Nierengurt",        priceMin: 20,  priceMax: 30,  reason: "Einstieg, elastisch, verstellbar", image: "/gear/buse-stream-nierengurt.webp", amazon: "B003YGNKLI" },
    { name: "Held Nierengurt Comfort",   type: "Nierengurt Gepolst.",priceMin: 30,  priceMax: 60,  reason: "Breiter Schutz, Klettverschluss" , url: "https://www.fc-moto.com/de-de/p/held-falun-ii-nierengurt-HE-Held-Falun-II-Kidney-Belt.v", image: "/gear/held-nierengurt-comfort.webp", },
    { name: "Held Tri-Tec Nierengurt",         type: "Nierengurt Premium", priceMin: 60,  priceMax: 80, reason: "Breit, stützend, atmungsaktiv", image: "/gear/held-tri-tec-nierengurt.webp", amazon: "B00XDC9UVC" },
    { name: "Vanucci 2-in-1 Nierengurt", type: "Nierengurt", priceMin: 40, priceMax: 40, reason: "", image: "/gear/vanucci-2-in-1-nierengurt.webp", amazon: "B0BGHNDV38" },
    { name: "Held Mago", type: "Nierengurt (Damen)", priceMin: 30, priceMax: 40, reason: "", image: "/gear/held-mago.webp", amazon: "B001MU9VC0" },
    { name: "IXS Tex-Belt III", type: "Nierengurt", priceMin: 20, priceMax: 20, reason: "", image: "/gear/ixs-tex-belt-iii.webp", amazon: "B07DVVHLQM" },
    { name: "IXS Zip", type: "Nierengurt", priceMin: 20, priceMax: 30, reason: "", image: "/gear/ixs-zip.webp", amazon: "B084LDMCXC" },
  ],
  balaclava: [
    { name: "Held Thermo Sturmhaube",    type: "Sturmhaube",        priceMin: 10,  priceMax: 20,  reason: "Warm, atmungsaktiv, Einstieg" , url: "https://www.fc-moto.com/de-de/p/held-9250-sturmhaube-HE-009250-00-1-Stck", image: "/gear/held-thermo-sturmhaube.webp", },
    { name: "Büse Coolmax Sturmhaube",   type: "Sturmhaube Sommer", priceMin: 10,  priceMax: 30,  reason: "Feuchtigkeitsregulierend, dünn" , url: "https://www.fc-moto.com/en-en/p/buese-balaclava-coolmax-BUE-177800", image: "/gear/buse-coolmax-sturmhaube.webp", amazon: "B00ORLJPDG" },
    { name: "Held Spyder Sturmhaube",   type: "Sturmhaube Premium", priceMin: 35,  priceMax: 45,  reason: "Warm, winddicht, gute Passform", image: "/gear/held-spyder-sturmhaube.webp", amazon: "B004BZZ6HM" },
    { name: "Alpinestars KX V2", type: "Sturmhaube", priceMin: 30, priceMax: 30, reason: "", image: "/gear/alpinestars-kx-v2.webp", amazon: "B08ZRWPQG7" },
    { name: "Dainese Dry Balaclava", type: "Sturmhaube", priceMin: 30, priceMax: 40, reason: "", image: "/gear/dainese-dry-balaclava.webp", amazon: "B0B6PWSXP1" },
    { name: "Rev'it Micro 2", type: "Sturmhaube", priceMin: 30, priceMax: 40, reason: "", image: "/gear/rev-it-micro-2.webp", amazon: "B0FSJPDTTS" },
    { name: "Oxford Warmdry", type: "Winter-Sturmhaube", priceMin: 10, priceMax: 20, reason: "", image: "/gear/oxford-warmdry.webp", amazon: "B0BT1MJ5QB" },
  ],
  backprotector: [
    { name: "Alpinestars Nucleon KR-1 Celli", type: "Rückenprotektor",   priceMin: 60,  priceMax: 80,  reason: "Leicht, flexibel, belüftet", image: "/gear/alpinestars-nucleon-kr-1-celli.webp", amazon: "B07X54BN8Q" },
    { name: "Held Exosafe D3O",           type: "Rückenprotektor",   priceMin: 50,  priceMax: 60, reason: "D3O-Schaum, ergonomisch geformt", image: "/gear/held-exosafe-d3o.webp", amazon: "B09QZK13R2" },
    { name: "Forcefield Pro Lite K",    type: "Rückenprotektor",   priceMin: 60, priceMax: 70, reason: "CE-Level 2, leicht und flach", image: "/gear/forcefield-pro-lite-k.webp", amazon: "B01GQ85BPS" },
    { name: "Dainese Pro-Armor Back 2.0", type: "Rückenprotektor Level 2", priceMin: 120, priceMax: 140, reason: "", image: "/gear/dainese-pro-armor-back-2-0.webp", amazon: "B0BXBFLLMM" },
    { name: "Büse Breeze", type: "Rückenprotektor", priceMin: 70, priceMax: 90, reason: "", image: "/gear/buse-breeze.webp", amazon: "B0CCLBF41K" },
    { name: "Alpinestars Nucleon Plasma", type: "Rückenprotektor-Einsatz Level 2", priceMin: 50, priceMax: 60, reason: "", image: "/gear/alpinestars-nucleon-plasma.webp", amazon: "B0CV8HS5T8" },
    { name: "ORTEMA Ortho-MAX Light", type: "Rückenprotektor Level 1", priceMin: 130, priceMax: 160, reason: "", image: "/gear/ortema-ortho-max-light.webp", amazon: "B07NRSSM7N" },
    { name: "Rev'it Seesoft Air", type: "Rückenprotektor", priceMin: 40, priceMax: 50, reason: "", amazon: "B09QJLC76M", image: "/gear/rev-it-seesoft-air.webp" },
    { name: "Dainese Wave 13 D1 Air", type: "Rückenprotektor", priceMin: 140, priceMax: 170, reason: "", amazon: "B00WABS4YG", image: "/gear/dainese-wave-13-d1-air.webp" },
  ],
}

const gearByStyle = {
  Sportbike: {
    helmet: [
      { name: "LS2 FF800 Storm II",        type: "Integralhelm",       priceMin: 90, priceMax: 200, reason: "Leicht, gut belüftet, Einstieg" , url: "https://www.fc-moto.com/de-de/p/ls2-ff800-storm-ii-solid-helm-titan-xs-53-54-LS-168001007XS", image: "/gear/ls2-ff800-storm-ii.webp", amazon: "B0CBMX42FG" },
      { name: "AGV K6 S",                  type: "Integralhelm",       priceMin: 250, priceMax: 400, reason: "Kompakt, aerodynamisch, alltagstauglich" , url: "https://www.louis.de/artikel/agv-k6-s-integralhelm/217335", image: "/gear/agv-k6-s.webp", amazon: "B0G35VN8RR" },
      { name: "Shoei NXR 2",        type: "Sport-Integralhelm",priceMin: 450, priceMax: 550, reason: "Leicht, leise, sportlicher Allrounder", image: "/gear/shoei-nxr-2.webp", amazon: "B0B82D9HQW" },
      { name: "HJC i71", type: "Integralhelm", priceMin: 130, priceMax: 160, reason: "", image: "/gear/hjc-i71.webp", amazon: "B0BMY7CHMX" },
      { name: "Scorpion EXO-530 Air", type: "Integralhelm", priceMin: 130, priceMax: 150, reason: "", image: "/gear/scorpion-exo-530-air.webp", amazon: "B0FY6D3HXK" },
      { name: "Shark Skwal i3", type: "Integralhelm", priceMin: 140, priceMax: 170, reason: "", image: "/gear/shark-skwal-i3.webp", amazon: "B0CGVMPSZ1" },
      { name: "Airoh Matryx", type: "Integralhelm", priceMin: 220, priceMax: 270, reason: "", image: "/gear/airoh-matryx.webp", amazon: "B0CNKQMWL7" },
      { name: "X-Lite X-803 RS Carbon", type: "Racing-Integralhelm", priceMin: 450, priceMax: 550, reason: "", amazon: "B07YZZWBLK", image: "/gear/x-lite-x-803-rs-carbon.webp" },
      { name: "Scorpion EXO-R1 Evo II Air", type: "Racing-Integralhelm", priceMin: 280, priceMax: 340, reason: "", amazon: "B0FXMK6GM7", image: "/gear/scorpion-exo-r1-evo-ii-air.webp" },
      { name: "Shark Spartan RS Carbon", type: "Integralhelm", priceMin: 280, priceMax: 350, reason: "", amazon: "B0CL9WPWG5", image: "/gear/shark-spartan-rs-carbon.webp" },
      { name: "Arai Quantic", type: "Premium-Integralhelm", priceMin: 640, priceMax: 790, reason: "", amazon: "B0DB26LT7T", image: "/gear/arai-quantic.webp" },
      { name: "Airoh Spark 2", type: "Integralhelm", priceMin: 80, priceMax: 100, reason: "", amazon: "B0DLBHHPYB", image: "/gear/airoh-spark-2.webp" },
      { name: "AGV K3", type: "Integralhelm", priceMin: 150, priceMax: 190, reason: "", amazon: "B0BJFKV4VZ", image: "/gear/agv-k3.webp" },
      { name: "AGV K1 S", type: "Sport-Integralhelm", priceMin: 140, priceMax: 170, reason: "", amazon: "B0FHJN9N3D", image: "/gear/agv-k1-s.webp" },
      { name: "MT Stinger 2", type: "Integralhelm", priceMin: 70, priceMax: 90, reason: "", amazon: "B0FTMPH6B5", image: "/gear/mt-stinger-2.webp" },
      { name: "MT Targo S", type: "Integralhelm", priceMin: 110, priceMax: 130, reason: "", amazon: "B0FTMWKSH2", image: "/gear/mt-targo-s.webp" },
    ],
    jacket: [
      { name: "Alpinestars T-SPS Air V2",      type: "Textiljacke",        priceMin: 160, priceMax: 200, reason: "Stark belüftet, sportliche Passform", image: "/gear/alpinestars-t-sps-air-v2.webp", amazon: "B0DXZXW8GL" },
      { name: "Rev'it Quantum 2",          type: "Textiljacke",        priceMin: 200, priceMax: 350, reason: "CE-Level 2, vielseitig, belüftet" , url: "https://www.amazon.de/REVIT-Motorradjacke-Protektoren-Textiljacke-Ganzj%C3%A4hrig/dp/B08X1PVWGT", image: "/gear/revit-quantum-2.webp", },
      { name: "Alpinestars GP Plus R v3",  type: "Lederkombi",         priceMin: 350, priceMax: 550, reason: "CE-Level 2, Racing-Passform" , url: "https://www.louis.de/artikel/alpinestars-gp-plus-r-v3-lederkombijacke/207588", image: "/gear/alpinestars-gp-plus-r-v3.webp", amazon: "B08WK7CM6M" },
      { name: "Rev'it Eclipse 2 Jacke", type: "Sommer-Mesh-Jacke", priceMin: 120, priceMax: 150, reason: "", image: "/gear/rev-it-eclipse-2-jacke.webp", amazon: "B0BRQHTF3S" },
      { name: "Alpinestars ST-1 WP", type: "Touring-Textiljacke", priceMin: 180, priceMax: 230, reason: "", image: "/gear/alpinestars-st-1-wp.webp", amazon: "B0F19G5GYG" },
      { name: "Spidi Super Net", type: "Sommer-Mesh-Jacke", priceMin: 130, priceMax: 150, reason: "", image: "/gear/spidi-super-net.webp", amazon: "B0BF5RC9TL" },
      { name: "Spidi 4 Season V3 H2Out", type: "Touring-Textiljacke", priceMin: 410, priceMax: 500, reason: "", image: "/gear/spidi-4-season-v3-h2out.webp", amazon: "B0FC8LKGL2" },
      { name: "Dainese Racing 5", type: "Sport-Lederjacke", priceMin: 470, priceMax: 580, reason: "", image: "/gear/dainese-racing-5.webp", amazon: "B0DT7GCZ7R" },
      { name: "Dainese Super Speed 4", type: "Sport-Lederjacke", priceMin: 510, priceMax: 620, reason: "", image: "/gear/dainese-super-speed-4.webp", amazon: "B0BGBS6FY3" },
      { name: "Dainese Avro 5", type: "Sport-Lederjacke", priceMin: 460, priceMax: 570, reason: "", image: "/gear/dainese-avro-5.webp", amazon: "B0CMHXZLX6" },
      { name: "Oxford Rainseal", type: "Regenüberjacke", priceMin: 50, priceMax: 60, reason: "", image: "/gear/oxford-rainseal.webp", amazon: "B0BL1HB5YQ" },
      { name: "Spidi Netrunner H2Out", type: "Sommer-Meshjacke", priceMin: 210, priceMax: 260, reason: "", image: "/gear/spidi-netrunner-h2out.webp", amazon: "B07Q2KRH3C" },
    ],
    gloves: [
      { name: "Held Sambia",               type: "Sporthandschuhe",    priceMin: 30,  priceMax: 80,  reason: "Einstieg, guter Grip" , url: "https://www.fc-moto.com/de-de/p/held-sambia-adventure-motorrad-handschuhe-schwarz-7-s-HE-002163-00-1-7", image: "/gear/held-sambia.webp", amazon: "B004Y4QQ60" },
      { name: "Alpinestars SP-8 v3",       type: "Sporthandschuhe",    priceMin: 60,  priceMax: 100, reason: "Kurze Manschette, direktes Feeling" , url: "https://www.louis.de/artikel/alpinestars-sp-8-v3-handschuhe/210662", image: "/gear/alpinestars-sp-8-v3.webp", amazon: "B08WH6TLFS" },
      { name: "Held Phantom II",           type: "Race-Handschuhe",    priceMin: 120, priceMax: 200, reason: "Kangaroo-Leder, maximaler Schutz" , url: "https://www.louis.de/artikel/held-phantom-ii-2312-handschuhe/201364", image: "/gear/held-phantom-ii.webp", amazon: "B00AL6UWAG" },
      { name: "Rev'it Veloz", type: "Sport-Kurzhandschuh", priceMin: 50, priceMax: 70, reason: "", image: "/gear/rev-it-veloz.webp", amazon: "B0GRJQM9ST" },
      { name: "Dainese Ermex", type: "Sommer mit Mesh", priceMin: 50, priceMax: 70, reason: "", image: "/gear/dainese-ermex.webp", amazon: "B0DRHWGXF4" },
      { name: "Alpinestars SP-3", type: "Kurzer Sporthandschuh", priceMin: 70, priceMax: 80, reason: "", image: "/gear/alpinestars-sp-3.webp", amazon: "B0DXYRDMGB" },
      { name: "Spidi Flash-R Evo", type: "Sommer mit Protektoren", priceMin: 50, priceMax: 70, reason: "", image: "/gear/spidi-flash-r-evo.webp", amazon: "B0793R4LHN" },
      { name: "Spidi Flash-R Evo Lady", type: "Damen-Sommer", priceMin: 40, priceMax: 50, reason: "", image: "/gear/spidi-flash-r-evo-lady.webp", amazon: "B07D19K9RY" },
      { name: "Spidi STR-6", type: "Racing mit Stulpe", priceMin: 130, priceMax: 150, reason: "", image: "/gear/spidi-str-6.webp", amazon: "B0BV9MY1GP" },
      { name: "Five RS-C", type: "Kurzer Stadthandschuh", priceMin: 70, priceMax: 90, reason: "", image: "/gear/five-rs-c.webp", amazon: "B0D6GQ2VV2" },
      { name: "Furygan TD21", type: "Sommer-Leder", priceMin: 60, priceMax: 70, reason: "", image: "/gear/furygan-td21.webp", amazon: "B09GG1B187" },
      { name: "Knox Orsa Leather MK3", type: "Leder mit Kahnbeinschutz", priceMin: 140, priceMax: 170, reason: "", image: "/gear/knox-orsa-leather-mk3.webp", amazon: "B0FCYQ9THG" },
      { name: "Macna Haros 2.0", type: "Kurzer Sporthandschuh", priceMin: 50, priceMax: 60, reason: "", image: "/gear/macna-haros-2-0.webp", amazon: "B0F99TSJZ9" },
      { name: "Richa Turbo", type: "Racing mit Stulpe", priceMin: 60, priceMax: 70, reason: "", image: "/gear/richa-turbo.webp", amazon: "B01N6WO6KF" },
    ],
    boots: [
      { name: "TCX Comp Evo 2",            type: "Sport-Stiefel",      priceMin: 100, priceMax: 250, reason: "Solider Knöchelschutz, gute Passform" , url: "https://www.fc-moto.com/de-de/p/tcx-comp-evo-2-michelin-motocross-stiefel-blau-rot-38-TCX-9662-RBBY-38", image: "/gear/tcx-comp-evo-2.webp", amazon: "B08N1KZS3S" },
      { name: "Sidi Rex",          type: "Rennsportstiefel",   priceMin: 300, priceMax: 370, reason: "Racing-Stiefel, hoher Knöchelschutz", image: "/gear/sidi-rex.webp", amazon: "B0CJFH1TTT" },
      { name: "Alpinestars Supertech R",   type: "Racing-Stiefel",     priceMin: 300, priceMax: 640, reason: "Maximaler Schutz, Rennstrecke" , url: "https://www.louis.de/artikel/alpinestars-supertech-r-stiefel/202464", image: "/gear/alpinestars-supertech-r.webp", amazon: "B08WVGHF4R" },
      { name: "Dainese Nexus 3 Air", type: "Racing, belüftet", priceMin: 270, priceMax: 330, reason: "", image: "/gear/dainese-nexus-3-air.webp", amazon: "B0GNSMWMDZ" },
      { name: "Dainese Metractive Air", type: "Urban-Sneaker belüftet", priceMin: 130, priceMax: 160, reason: "", image: "/gear/dainese-metractive-air.webp", amazon: "B0BQJHZZKK" },
      { name: "Alpinestars SMX-6 v2", type: "Sportstiefel", priceMin: 170, priceMax: 200, reason: "", image: "/gear/alpinestars-smx-6-v2.webp", amazon: "B0BMYB37D9" },
      { name: "TCX RT-Race Pro Air", type: "Racing-Stiefel belüftet", priceMin: 280, priceMax: 340, reason: "", image: "/gear/tcx-rt-race-pro-air.webp", amazon: "B09JVNJPDF" },
      { name: "Sidi Mag-1", type: "Racing-Stiefel", priceMin: 280, priceMax: 340, reason: "", image: "/gear/sidi-mag-1.webp", amazon: "B00U74R6B0" },
      { name: "Daytona Road Star GTX", type: "Tourenstiefel wasserdicht", priceMin: 360, priceMax: 440, reason: "", image: "/gear/daytona-road-star-gtx.webp", amazon: "B01BWM3984" },
    ],
    pants: [
      { name: "Rev'it Tornado 4",          type: "Textilhose",         priceMin: 150, priceMax: 300, reason: "CE-Level 2, belüftet, Sommer" , url: "https://www.fc-moto.com/de-de/p/revit-tornado-4-h2o-wasserdichte-motorrad-textilhose-silber-schwarz-s-REV-FPT138-4051-S", image: "/gear/revit-tornado-4.webp", amazon: "B0CY4MCTDF" },
      { name: "Alpinestars Andes v3 Pant", type: "Textilhose",         priceMin: 110, priceMax: 320, reason: "Wasserdicht, touring-tauglich" , url: "https://www.fc-moto.com/en-en/p/alpinestars-andes-v3-drystar-motorcycle-textile-pants-black-m-APS-3227521-10-M", image: "/gear/alpinestars-andes-v3-pant.webp", amazon: "B08HPC8M47" },
      { name: "Alpinestars Missile V3",    type: "Lederhose",          priceMin: 330, priceMax: 400, reason: "Racing-Passform, Leder", image: "/gear/alpinestars-missile-v3.webp", amazon: "B09VZXDQMT" },
      { name: "Rev'it Eclipse 2", type: "Textil-Sommerhose", priceMin: 100, priceMax: 120, reason: "", image: "/gear/rev-it-eclipse-2.webp", amazon: "B0BX761SYL" },
      { name: "Dainese Drake 2 Super Air Tex", type: "Mesh-Sommerhose", priceMin: 170, priceMax: 210, reason: "", image: "/gear/dainese-drake-2-super-air-tex.webp", amazon: "B0CY2RLKPB" },
      { name: "Spidi Superstorm H2Out", type: "Regenhose", priceMin: 120, priceMax: 140, reason: "", image: "/gear/spidi-superstorm-h2out.webp", amazon: "B007K5A6PM" },
      { name: "Alpinestars Hurricane V2", type: "Regen-Überhose", priceMin: 50, priceMax: 60, reason: "", image: "/gear/alpinestars-hurricane-v2.webp", amazon: "B0DW7R1R91" },
      { name: "Dainese Drake 2 Air Tex", type: "Sommer-Textilhose", priceMin: 200, priceMax: 240, reason: "", amazon: "B0CWVJY82F", image: "/gear/dainese-drake-2-air-tex.webp" },
      { name: "Dainese Storm 2", type: "Regen-Überhose", priceMin: 90, priceMax: 100, reason: "", image: "/gear/dainese-storm-2.webp", amazon: "B08L3FC3NK" },
      { name: "Macna Bora", type: "Sommer-Mesh-Hose", priceMin: 80, priceMax: 90, reason: "", image: "/gear/macna-bora.webp", amazon: "B07ZTKGN1D" },
      { name: "Furygan Phenix", type: "Textil-Tourenhose", priceMin: 140, priceMax: 170, reason: "", amazon: "B0CX1D8K2L", image: "/gear/furygan-phenix.webp" },
    ],
    ...universalGear,
  },
  Naked: {
    helmet: [
      { name: "Schuberth C4 Basic",        type: "Klapphelm",          priceMin: 150, priceMax: 290, reason: "Praktisch für Alltag, sicher" , url: "https://www.fc-moto.com/de-de/p/schuberth-c4-basic-helm-silber-xs-53-54-SUB-4546513360", image: "/gear/schuberth-c4-basic.webp", amazon: "B07RZTJBP6" },
      { name: "AGV K6 S",                  type: "Integralhelm",       priceMin: 250, priceMax: 400, reason: "Kompakt, leicht, alltagstauglich" , url: "https://www.louis.de/artikel/agv-k6-s-integralhelm/217335", image: "/gear/agv-k6-s.webp", amazon: "B0G35VN8RR" },
      { name: "Shoei NXR2",                type: "Integralhelm",       priceMin: 380, priceMax: 550, reason: "Exzellente Belüftung, leiser Innenraum" , url: "https://www.louis.de/artikel/shoei-nxr-2-integralhelm/217554", image: "/gear/shoei-nxr2.webp", amazon: "B0B82D9HQW" },
      { name: "HJC i71", type: "Integralhelm", priceMin: 130, priceMax: 160, reason: "", image: "/gear/hjc-i71.webp", amazon: "B0BMY7CHMX" },
      { name: "Nolan N100-6", type: "Klapphelm", priceMin: 240, priceMax: 300, reason: "", image: "/gear/nolan-n100-6.webp", amazon: "B0DJR9698M" },
      { name: "Caberg Duke X", type: "Klapphelm", priceMin: 140, priceMax: 180, reason: "", image: "/gear/caberg-duke-x.webp", amazon: "B0BNVNCCR1" },
      { name: "Scorpion EXO-530 Air", type: "Integralhelm", priceMin: 130, priceMax: 150, reason: "", image: "/gear/scorpion-exo-530-air.webp", amazon: "B0FY6D3HXK" },
      { name: "Shark Skwal i3", type: "Integralhelm", priceMin: 140, priceMax: 170, reason: "", image: "/gear/shark-skwal-i3.webp", amazon: "B0CGVMPSZ1" },
      { name: "Airoh Matryx", type: "Integralhelm", priceMin: 220, priceMax: 270, reason: "", image: "/gear/airoh-matryx.webp", amazon: "B0CNKQMWL7" },
      { name: "Arai Tour-X5", type: "Adventurehelm", priceMin: 400, priceMax: 490, reason: "", image: "/gear/arai-tour-x5.webp", amazon: "B0DLX6NXR6" },
      { name: "Nolan N80-8", type: "Integralhelm", priceMin: 190, priceMax: 230, reason: "", amazon: "B0DK24JGBJ", image: "/gear/nolan-n80-8.webp" },
      { name: "Caberg Horus X", type: "Klapphelm", priceMin: 200, priceMax: 240, reason: "", amazon: "B0C33ZDKW9", image: "/gear/caberg-horus-x.webp" },
      { name: "Scorpion EXO-R1 Evo II Air", type: "Racing-Integralhelm", priceMin: 280, priceMax: 340, reason: "", amazon: "B0FXMK6GM7", image: "/gear/scorpion-exo-r1-evo-ii-air.webp" },
      { name: "Shark Spartan RS Carbon", type: "Integralhelm", priceMin: 280, priceMax: 350, reason: "", amazon: "B0CL9WPWG5", image: "/gear/shark-spartan-rs-carbon.webp" },
      { name: "Arai Quantic", type: "Premium-Integralhelm", priceMin: 640, priceMax: 790, reason: "", amazon: "B0DB26LT7T", image: "/gear/arai-quantic.webp" },
      { name: "LS2 Advant X Carbon", type: "Klapphelm 180°", priceMin: 300, priceMax: 360, reason: "", amazon: "B0BRQ8774H", image: "/gear/ls2-advant-x-carbon.webp" },
      { name: "Airoh Spark 2", type: "Integralhelm", priceMin: 80, priceMax: 100, reason: "", amazon: "B0DLBHHPYB", image: "/gear/airoh-spark-2.webp" },
      { name: "AGV K3", type: "Integralhelm", priceMin: 150, priceMax: 190, reason: "", amazon: "B0BJFKV4VZ", image: "/gear/agv-k3.webp" },
      { name: "AGV K1 S", type: "Sport-Integralhelm", priceMin: 140, priceMax: 170, reason: "", amazon: "B0FHJN9N3D", image: "/gear/agv-k1-s.webp" },
      { name: "MT Stinger 2", type: "Integralhelm", priceMin: 70, priceMax: 90, reason: "", amazon: "B0FTMPH6B5", image: "/gear/mt-stinger-2.webp" },
      { name: "MT Targo S", type: "Integralhelm", priceMin: 110, priceMax: 130, reason: "", amazon: "B0FTMWKSH2", image: "/gear/mt-targo-s.webp" },
    ],
    jacket: [
      { name: "Held Carese Evo",           type: "Textiljacke",        priceMin: 120, priceMax: 710, reason: "Vielseitig, wasserdicht, CE-Level 1" , url: "https://www.fc-moto.com/de-de/p/held-carese-evo-gtx-motorrad-textiljacke-hellgrau-rot-lang-m-HE-062140-00-72-L-M", image: "/gear/held-carese-evo.webp", amazon: "B0BHNJBZV2" },
      { name: "Rev'it Quantum 2",          type: "Textiljacke",        priceMin: 200, priceMax: 350, reason: "CE-Level 2, belüftet, alltagstauglich" , url: "https://www.amazon.de/REVIT-Motorradjacke-Protektoren-Textiljacke-Ganzj%C3%A4hrig/dp/B08X1PVWGT", image: "/gear/revit-quantum-2.webp", },
      { name: "Furygan Raptor Evo 3",            type: "Lederjacke",         priceMin: 320, priceMax: 390, reason: "Sportliche Lederjacke, gute Passform", image: "/gear/furygan-raptor-evo-3.webp", amazon: "B0G3N27K6Y" },
      { name: "Rev'it Tornado 4 H2O Jacke", type: "Adventure-Textiljacke", priceMin: 290, priceMax: 350, reason: "", image: "/gear/rev-it-tornado-4-h2o-jacke.webp", amazon: "B0CWDHJ624" },
      { name: "Rev'it Eclipse 2 Jacke", type: "Sommer-Mesh-Jacke", priceMin: 120, priceMax: 150, reason: "", image: "/gear/rev-it-eclipse-2-jacke.webp", amazon: "B0BRQHTF3S" },
      { name: "Held Tourino Top", type: "Touring-Textiljacke", priceMin: 130, priceMax: 160, reason: "", image: "/gear/held-tourino-top.webp", amazon: "B09QHHHVWT" },
      { name: "IXS Evo-Air", type: "Sommer-Mesh-Jacke", priceMin: 60, priceMax: 70, reason: "", image: "/gear/ixs-evo-air.webp", amazon: "B08NPHY8B1" },
      { name: "Macna Tryton NightEye", type: "Leder-/Textiljacke", priceMin: 310, priceMax: 370, reason: "", image: "/gear/macna-tryton-nighteye.webp", amazon: "B0F14RDHDV" },
      { name: "Alpinestars ST-1 WP", type: "Touring-Textiljacke", priceMin: 180, priceMax: 230, reason: "", image: "/gear/alpinestars-st-1-wp.webp", amazon: "B0F19G5GYG" },
      { name: "Spidi Super Net", type: "Sommer-Mesh-Jacke", priceMin: 130, priceMax: 150, reason: "", image: "/gear/spidi-super-net.webp", amazon: "B0BF5RC9TL" },
      { name: "Spidi 4 Season V3 H2Out", type: "Touring-Textiljacke", priceMin: 410, priceMax: 500, reason: "", image: "/gear/spidi-4-season-v3-h2out.webp", amazon: "B0FC8LKGL2" },
      { name: "Dainese Racing 5", type: "Sport-Lederjacke", priceMin: 470, priceMax: 580, reason: "", image: "/gear/dainese-racing-5.webp", amazon: "B0DT7GCZ7R" },
      { name: "Büse Lago III", type: "Textil-Tourenjacke", priceMin: 170, priceMax: 210, reason: "", image: "/gear/buse-lago-iii.webp", amazon: "B0GHNTXKTK" },
      { name: "Büse Lago III Damen", type: "Damen-Textiljacke", priceMin: 170, priceMax: 200, reason: "", image: "/gear/buse-lago-iii-damen.webp", amazon: "B0GHNK341Y" },
      { name: "Büse Livorno", type: "Sommer-Meshjacke", priceMin: 140, priceMax: 180, reason: "", image: "/gear/buse-livorno.webp", amazon: "B0C53KYF2Y" },
      { name: "Dainese Super Speed 4", type: "Sport-Lederjacke", priceMin: 510, priceMax: 620, reason: "", image: "/gear/dainese-super-speed-4.webp", amazon: "B0BGBS6FY3" },
      { name: "Dainese Avro 5", type: "Sport-Lederjacke", priceMin: 460, priceMax: 570, reason: "", image: "/gear/dainese-avro-5.webp", amazon: "B0CMHXZLX6" },
      { name: "Alpinestars Halo Drystar", type: "Adventure-Textiljacke", priceMin: 340, priceMax: 410, reason: "", image: "/gear/alpinestars-halo-drystar.webp", amazon: "B09WXSW23X" },
      { name: "Alpinestars Stella Andes V4", type: "Damen-Tourenjacke", priceMin: 240, priceMax: 300, reason: "", image: "/gear/alpinestars-stella-andes-v4.webp", amazon: "B0FR3RQG5G" },
      { name: "Held Zorro ST Top", type: "Allwetter-Textiljacke", priceMin: 180, priceMax: 220, reason: "", image: "/gear/held-zorro-st-top.webp", amazon: "B0FTZJDD39" },
      { name: "Richa Infinity 2 Damen", type: "Damen-Textiljacke", priceMin: 150, priceMax: 190, reason: "", image: "/gear/richa-infinity-2-damen.webp", amazon: "B0883FDFYQ" },
      { name: "Modeka Clarke", type: "Textil-Tourenjacke", priceMin: 90, priceMax: 110, reason: "", image: "/gear/modeka-clarke.webp", amazon: "B07J6JKDTM" },
      { name: "Oxford Rainseal", type: "Regenüberjacke", priceMin: 50, priceMax: 60, reason: "", image: "/gear/oxford-rainseal.webp", amazon: "B0BL1HB5YQ" },
      { name: "Spidi Netrunner H2Out", type: "Sommer-Meshjacke", priceMin: 210, priceMax: 260, reason: "", image: "/gear/spidi-netrunner-h2out.webp", amazon: "B07Q2KRH3C" },
    ],
    gloves: [
      { name: "Held Hamada",               type: "Kurzhandschuhe",     priceMin: 30,  priceMax: 60,  reason: "Guter Grip, handlich im Alltag" , url: "https://www.louis.de/artikel/held-hamada-22060-handschuhe/201704", image: "/gear/held-hamada.webp", amazon: "B0FTTW63GN" },
      { name: "Alpinestars Andes v3",      type: "Allwetter",          priceMin: 60,  priceMax: 120, reason: "Wasserdicht, vielseitig" , url: "https://eu.alpinestars.com/products/andes-v3-drystar-glove-black", image: "/gear/alpinestars-andes-v3.webp", amazon: "B0BPK2K6TP" },
      { name: "Held Air Stream 3",         type: "Sommer-Handschuhe",  priceMin: 100, priceMax: 160, reason: "Maximale Belüftung, CE-Level 2" , url: "https://www.louis.de/artikel/held-air-stream-3-0-handschuhe/201851", image: "/gear/held-air-stream-3.webp", amazon: "B07ZYVPQ9D" },
      { name: "Dainese Teyde Gore-Tex", type: "Winter-Touring, wasserdicht", priceMin: 100, priceMax: 120, reason: "", image: "/gear/dainese-teyde-gore-tex.webp", amazon: "B0DPHSBGZD" },
      { name: "Rev'it Mangrove 2", type: "Adventure-Sommer", priceMin: 60, priceMax: 70, reason: "", image: "/gear/rev-it-mangrove-2.webp", amazon: "B0GRCP71S6" },
      { name: "Rev'it Veloz", type: "Sport-Kurzhandschuh", priceMin: 50, priceMax: 70, reason: "", image: "/gear/rev-it-veloz.webp", amazon: "B0GRJQM9ST" },
      { name: "Rev'it Access", type: "Urban-Sommer", priceMin: 30, priceMax: 40, reason: "", image: "/gear/rev-it-access.webp", amazon: "B0CZSDGH3F" },
      { name: "IXS Arctic-GTX 2.0", type: "Winter Gore-Tex", priceMin: 70, priceMax: 90, reason: "", image: "/gear/ixs-arctic-gtx-2-0.webp", amazon: "B08NFQ3BF9" },
      { name: "Büse Brandon", type: "Touring, wasserdicht", priceMin: 50, priceMax: 70, reason: "", image: "/gear/buse-brandon.webp", amazon: "B0CCL9LF69" },
      { name: "Dainese Mig 3", type: "Kurzer Lederhandschuh", priceMin: 40, priceMax: 50, reason: "", image: "/gear/dainese-mig-3.webp", amazon: "B0CMJHSN8R" },
      { name: "Dainese Ermex", type: "Sommer mit Mesh", priceMin: 50, priceMax: 70, reason: "", image: "/gear/dainese-ermex.webp", amazon: "B0DRHWGXF4" },
      { name: "Dainese Tempest 2 D-Dry", type: "Touring wasserdicht", priceMin: 90, priceMax: 110, reason: "", image: "/gear/dainese-tempest-2-d-dry.webp", amazon: "B0CJ768NHY" },
      { name: "Alpinestars SP-3", type: "Kurzer Sporthandschuh", priceMin: 70, priceMax: 80, reason: "", image: "/gear/alpinestars-sp-3.webp", amazon: "B0DXYRDMGB" },
      { name: "Alpinestars Stella Copper", type: "Damen-Sommer", priceMin: 40, priceMax: 50, reason: "", image: "/gear/alpinestars-stella-copper.webp", amazon: "B07TWNV8FX" },
      { name: "Spidi Flash-R Evo", type: "Sommer mit Protektoren", priceMin: 50, priceMax: 70, reason: "", image: "/gear/spidi-flash-r-evo.webp", amazon: "B0793R4LHN" },
      { name: "Spidi Flash-R Evo Lady", type: "Damen-Sommer", priceMin: 40, priceMax: 50, reason: "", image: "/gear/spidi-flash-r-evo-lady.webp", amazon: "B07D19K9RY" },
      { name: "Spidi Wintertourer-KP", type: "Winterhandschuh", priceMin: 70, priceMax: 80, reason: "", image: "/gear/spidi-wintertourer-kp.webp", amazon: "B0DTMQFHHF" },
      { name: "Five RS-C", type: "Kurzer Stadthandschuh", priceMin: 70, priceMax: 90, reason: "", image: "/gear/five-rs-c.webp", amazon: "B0D6GQ2VV2" },
      { name: "Furygan TD21", type: "Sommer-Leder", priceMin: 60, priceMax: 70, reason: "", image: "/gear/furygan-td21.webp", amazon: "B09GG1B187" },
      { name: "Furygan Yakuru D3O WP", type: "Allwetter wasserdicht", priceMin: 60, priceMax: 70, reason: "", image: "/gear/furygan-yakuru-d3o-wp.webp", amazon: "B0BXDJTTGZ" },
      { name: "Knox Orsa Leather MK3", type: "Leder mit Kahnbeinschutz", priceMin: 140, priceMax: 170, reason: "", image: "/gear/knox-orsa-leather-mk3.webp", amazon: "B0FCYQ9THG" },
      { name: "Macna Haros 2.0", type: "Kurzer Sporthandschuh", priceMin: 50, priceMax: 60, reason: "", image: "/gear/macna-haros-2-0.webp", amazon: "B0F99TSJZ9" },
    ],
    boots: [
      { name: "TCX Street 3",              type: "Sneaker-Stiefel",    priceMin: 80,  priceMax: 170, reason: "Alltagsoptik mit Schutzfunktion" , url: "https://www.louis.de/artikel/tcx-street-3-air-stiefel/219835", image: "/gear/tcx-street-3.webp", amazon: "B0BXSNN855" },
      { name: "Forma Phantom Flow",                type: "Sport-Stiefel",      priceMin: 260, priceMax: 320, reason: "Sportstiefel, belüftete Flow-Version", image: "/gear/forma-phantom-flow.webp", amazon: "B0BMVHV8M3" },
      { name: "Sidi Performer Gore",              type: "Touring-Stiefel",    priceMin: 250, priceMax: 310, reason: "Gore-Tex, sportlicher Touring-Stiefel", image: "/gear/sidi-performer-gore.webp", amazon: "B076Q24DV3" },
      { name: "TCX Clima 2 Surround GTX", type: "Touring Gore-Tex", priceMin: 240, priceMax: 290, reason: "", image: "/gear/tcx-clima-2-surround-gtx.webp", amazon: "B0BXSLWZBZ" },
      { name: "TCX Explorer.4 GTX", type: "Adventure-Stiefel", priceMin: 200, priceMax: 240, reason: "", image: "/gear/tcx-explorer-4-gtx.webp", amazon: "B0GYFNZKNN" },
      { name: "Forma Terra Evo Low WP", type: "Kurzer Adventure-Stiefel", priceMin: 250, priceMax: 310, reason: "", image: "/gear/forma-terra-evo-low-wp.webp", amazon: "B07ZTK3KRD" },
      { name: "Stylmartin Atom", type: "Urban-Sneaker", priceMin: 160, priceMax: 190, reason: "", image: "/gear/stylmartin-atom.webp", amazon: "B072PW25HR" },
      { name: "Daytona Journey GTX", type: "Touring Gore-Tex", priceMin: 280, priceMax: 350, reason: "", image: "/gear/daytona-journey-gtx.webp", amazon: "B004UAI6A2" },
      { name: "Rev'it Arrow 2 H2O", type: "Urban-Sneaker, wasserdicht", priceMin: 130, priceMax: 160, reason: "", image: "/gear/rev-it-arrow-2-h2o.webp", amazon: "B0GQ665BQN" },
      { name: "Dainese Dover Gore-Tex", type: "Urban-Schuh wasserdicht", priceMin: 300, priceMax: 360, reason: "", image: "/gear/dainese-dover-gore-tex.webp", amazon: "B07Y2L1R48" },
      { name: "Dainese Metractive Air", type: "Urban-Sneaker belüftet", priceMin: 130, priceMax: 160, reason: "", image: "/gear/dainese-metractive-air.webp", amazon: "B0BQJHZZKK" },
      { name: "Alpinestars SMX-6 v2", type: "Sportstiefel", priceMin: 170, priceMax: 200, reason: "", image: "/gear/alpinestars-smx-6-v2.webp", amazon: "B0BMYB37D9" },
      { name: "Gaerne G-Zion Gore-Tex", type: "Urban-Schuh wasserdicht", priceMin: 150, priceMax: 180, reason: "", image: "/gear/gaerne-g-zion-gore-tex.webp", amazon: "B0H4PD52KZ" },
      { name: "Gaerne G-Rome GTX", type: "Urban-Schuh wasserdicht", priceMin: 160, priceMax: 200, reason: "", image: "/gear/gaerne-g-rome-gtx.webp", amazon: "B0FFGF3JCN" },
      { name: "Stylmartin Iron", type: "Urban-Sneaker", priceMin: 160, priceMax: 200, reason: "", image: "/gear/stylmartin-iron.webp", amazon: "B0727R486Y" },
      { name: "Daytona Road Star GTX", type: "Tourenstiefel wasserdicht", priceMin: 360, priceMax: 440, reason: "", image: "/gear/daytona-road-star-gtx.webp", amazon: "B01BWM3984" },
      { name: "Falco Lennox 3", type: "Urban-Schuh", priceMin: 130, priceMax: 160, reason: "", image: "/gear/falco-lennox-3.webp", amazon: "B0FTZFX1BD" },
      { name: "IXS 2-Zip-SYM 2.0", type: "Tourenstiefel wasserdicht", priceMin: 80, priceMax: 90, reason: "", image: "/gear/ixs-2-zip-sym-2-0.webp", amazon: "B09V6L4NVR" },
    ],
    pants: [
      { name: "Büse Ferno",          type: "Textilhose",      priceMin: 80,  priceMax: 150, reason: "Alltagsoptik, CE-Level 1 Protektoren" , url: "https://www.amazon.de/dp/B081FD86H9", image: "/gear/buese-ferno-jeans.webp", },
      { name: "Rev'it Lombard 3",          type: "Motorradjeans",      priceMin: 150, priceMax: 250, reason: "Stretch-Denim, CE-Level 2" , url: "https://www.fc-moto.com/de-de/p/revit-lombard-3-rf-motorrad-jeans-dunkelgrau-30-l36-REV-FPJ054-6163-30", image: "/gear/revit-lombard-3.webp", amazon: "B09SX89S66" },
      { name: "Held Stockton Slim",         type: "Motorradjeans",      priceMin: 180, priceMax: 220, reason: "Schmale Jeans-Optik mit Protektoren-Taschen", image: "/gear/held-stockton-slim.webp", amazon: "B0G2WK5V3C" },
      { name: "Rev'it Eclipse 2", type: "Textil-Sommerhose", priceMin: 100, priceMax: 120, reason: "", image: "/gear/rev-it-eclipse-2.webp", amazon: "B0BX761SYL" },
      { name: "Dainese Drake 2 Super Air Tex", type: "Mesh-Sommerhose", priceMin: 170, priceMax: 210, reason: "", image: "/gear/dainese-drake-2-super-air-tex.webp", amazon: "B0CY2RLKPB" },
      { name: "Held Lonborg Base", type: "Adventure-Textilhose", priceMin: 270, priceMax: 330, reason: "", image: "/gear/held-lonborg-base.webp", amazon: "B0DWY1KRCH" },
      { name: "IXS Shape-ST", type: "Touring-Textilhose", priceMin: 150, priceMax: 180, reason: "", image: "/gear/ixs-shape-st.webp", amazon: "B0847QZHJF" },
      { name: "Spidi Superstorm H2Out", type: "Regenhose", priceMin: 120, priceMax: 140, reason: "", image: "/gear/spidi-superstorm-h2out.webp", amazon: "B007K5A6PM" },
      { name: "Alpinestars Hurricane V2", type: "Regen-Überhose", priceMin: 50, priceMax: 60, reason: "", image: "/gear/alpinestars-hurricane-v2.webp", amazon: "B0DW7R1R91" },
      { name: "Shima Devon", type: "Motorradjeans Slim", priceMin: 90, priceMax: 110, reason: "", image: "/gear/shima-devon.webp", amazon: "B09WDMFWX1" },
      { name: "Dainese Tempest 4 D-Dry", type: "Tourenhose wasserdicht", priceMin: 220, priceMax: 270, reason: "", image: "/gear/dainese-tempest-4-d-dry.webp", amazon: "B0HF8FTQRF" },
      { name: "Dainese Drake 2 Air Tex", type: "Sommer-Textilhose", priceMin: 200, priceMax: 240, reason: "", amazon: "B0CWVJY82F", image: "/gear/dainese-drake-2-air-tex.webp" },
      { name: "Dainese Storm 2", type: "Regen-Überhose", priceMin: 90, priceMax: 100, reason: "", image: "/gear/dainese-storm-2.webp", amazon: "B08L3FC3NK" },
      { name: "Richa Rain Warrior", type: "Regen-Überhose", priceMin: 40, priceMax: 50, reason: "", image: "/gear/richa-rain-warrior.webp", amazon: "B0041GIK2O" },
      { name: "Bull-it Icona II", type: "Damen-Motorradjeans", priceMin: 120, priceMax: 140, reason: "", amazon: "B09QJL9BM6", image: "/gear/bull-it-icona-ii.webp" },
      { name: "Bering Trust Tapered", type: "Damen-Motorradjeans", priceMin: 100, priceMax: 120, reason: "", amazon: "B0FBS5GQ3X", image: "/gear/bering-trust-tapered.webp" },
      { name: "Macna Bora", type: "Sommer-Mesh-Hose", priceMin: 80, priceMax: 90, reason: "", image: "/gear/macna-bora.webp", amazon: "B07ZTKGN1D" },
      { name: "Macna Bombar Jeans", type: "Motorradjeans", priceMin: 110, priceMax: 140, reason: "", image: "/gear/macna-bombar-jeans.webp", amazon: "B0C74JKPHP" },
      { name: "Modeka Bratt", type: "Motorradjeans", priceMin: 140, priceMax: 180, reason: "", amazon: "B0F38CLS4F", image: "/gear/modeka-bratt.webp" },
      { name: "Furygan Phenix", type: "Textil-Tourenhose", priceMin: 140, priceMax: 170, reason: "", amazon: "B0CX1D8K2L", image: "/gear/furygan-phenix.webp" },
      { name: "Furygan D12 X Kevlar", type: "Motorradjeans", priceMin: 150, priceMax: 190, reason: "", amazon: "B0FG7JJ9LY", image: "/gear/furygan-d12-x-kevlar.webp" },
    ],
    ...universalGear,
  },
  Cruiser: {
    helmet: [
      { name: "Biltwell Lane Splitter",         type: "Integral Custom",    priceMin: 310, priceMax: 380, reason: "Custom-Look, kompakte Schale", image: "/gear/biltwell-lane-splitter.webp", amazon: "B06Y28Y3N3" },
      { name: "Bell Bullitt",              type: "Retro-Integralhelm",      priceMin: 220, priceMax: 400, reason: "Klassischer Look, ECE 22.06" , url: "https://www.fc-moto.com/en-en/p/bell-bullitt-solid-helmet-black-matt-xs-54-55-BEL-8004720001", image: "/gear/bell-bullitt.webp", amazon: "B0FKN4VZ4H" },
      { name: "Hedon Heroine Racer",       type: "Integral Vintage",   priceMin: 850, priceMax: 950, reason: "Handgefertigt, Premium-Qualität", url: "https://www.24helmets.de/hedon-heroine-racer-2.0-signature-black-ece", image: "/gear/hedon-heroine-racer.webp" },
      { name: "Nolan N100-6", type: "Klapphelm", priceMin: 240, priceMax: 300, reason: "", image: "/gear/nolan-n100-6.webp", amazon: "B0DJR9698M" },
      { name: "Caberg Duke X", type: "Klapphelm", priceMin: 140, priceMax: 180, reason: "", image: "/gear/caberg-duke-x.webp", amazon: "B0BNVNCCR1" },
      { name: "LS2 Copter II", type: "Jethelm", priceMin: 100, priceMax: 120, reason: "", image: "/gear/ls2-copter-ii.webp", amazon: "B0C6R1P874" },
      { name: "Nolan N80-8", type: "Integralhelm", priceMin: 190, priceMax: 230, reason: "", amazon: "B0DK24JGBJ", image: "/gear/nolan-n80-8.webp" },
      { name: "Caberg Horus X", type: "Klapphelm", priceMin: 200, priceMax: 240, reason: "", amazon: "B0C33ZDKW9", image: "/gear/caberg-horus-x.webp" },
      { name: "LS2 Advant X Carbon", type: "Klapphelm 180°", priceMin: 300, priceMax: 360, reason: "", amazon: "B0BRQ8774H", image: "/gear/ls2-advant-x-carbon.webp" },
      { name: "Bell Custom 500", type: "Retro-Jethelm", priceMin: 180, priceMax: 220, reason: "", amazon: "B0DFCH3SFY", image: "/gear/bell-custom-500.webp" },
    ],
    jacket: [
      { name: "Helstons Tracker",         type: "Lederjacke Retro",   priceMin: 330, priceMax: 400, reason: "Vintage-Leder, klassischer Schnitt", image: "/gear/helstons-tracker.webp", amazon: "B08BZWJGLH" },
      { name: "Belstaff Trackmaster",       type: "Gewachste Baumwolle", priceMin: 540, priceMax: 660, reason: "Wasserdicht gewachst, Heritage-Klassiker", image: "/gear/belstaff-trackmaster.webp", amazon: "B0F6MC8P5W" },
      { name: "Furygan Clint Evo", type: "Retro-Lederjacke", priceMin: 250, priceMax: 310, reason: "", image: "/gear/furygan-clint-evo.webp", amazon: "B0B6PXT178" },
      { name: "Büse Livorno", type: "Sommer-Meshjacke", priceMin: 140, priceMax: 180, reason: "", image: "/gear/buse-livorno.webp", amazon: "B0C53KYF2Y" },
      { name: "Richa Infinity 2 Damen", type: "Damen-Textiljacke", priceMin: 150, priceMax: 190, reason: "", image: "/gear/richa-infinity-2-damen.webp", amazon: "B0883FDFYQ" },
      { name: "Modeka Clarke", type: "Textil-Tourenjacke", priceMin: 90, priceMax: 110, reason: "", image: "/gear/modeka-clarke.webp", amazon: "B07J6JKDTM" },
      { name: "Oxford Rainseal", type: "Regenüberjacke", priceMin: 50, priceMax: 60, reason: "", image: "/gear/oxford-rainseal.webp", amazon: "B0BL1HB5YQ" },
      { name: "IXS Classic SO 2.0", type: "Retro-Textiljacke", priceMin: 180, priceMax: 220, reason: "", image: "/gear/ixs-classic-so-2-0.webp", amazon: "B0C5RWJPM8" },
      { name: "Harley-Davidson Auroral 3in1", type: "Cruiser-Lederjacke", priceMin: 730, priceMax: 890, reason: "", image: "/gear/harley-davidson-auroral-3in1.webp", amazon: "B091H7DLS8" },
    ],
    gloves: [
      { name: "Biltwell Moto",             type: "Kurzhandschuh Synthetik", priceMin: 30, priceMax: 60,  reason: "Ikonisch, günstig, guter Grip", url: "https://shop.thunderbike.de/Bekleidung/Herren/Handschuhe/Biltwell-Moto-Gloves-Handschuhe-schwarz.html", image: "/gear/biltwell-moto.webp" },
      { name: "Held Steve",                type: "Touring-Leder",      priceMin: 60,  priceMax: 120, reason: "Langer Schaft, klassisches Design" , url: "https://www.fc-moto.com/de-de/p/held-steve-classic-motorrad-handschuhe-7-s-HE-002215-00-1-7", image: "/gear/held-steve.webp", },
      { name: "IXS Arctic-GTX 2.0", type: "Winter Gore-Tex", priceMin: 70, priceMax: 90, reason: "", image: "/gear/ixs-arctic-gtx-2-0.webp", amazon: "B08NFQ3BF9" },
      { name: "Büse Brandon", type: "Touring, wasserdicht", priceMin: 50, priceMax: 70, reason: "", image: "/gear/buse-brandon.webp", amazon: "B0CCL9LF69" },
      { name: "Büse Miles", type: "Retro-Leder perforiert", priceMin: 60, priceMax: 80, reason: "", image: "/gear/buse-miles.webp", amazon: "B0CCL7N1ZL" },
      { name: "Dainese Tempest 2 D-Dry", type: "Touring wasserdicht", priceMin: 90, priceMax: 110, reason: "", image: "/gear/dainese-tempest-2-d-dry.webp", amazon: "B0CJ768NHY" },
      { name: "Spidi Wintertourer-KP", type: "Winterhandschuh", priceMin: 70, priceMax: 80, reason: "", image: "/gear/spidi-wintertourer-kp.webp", amazon: "B0DTMQFHHF" },
      { name: "Five Oklahoma", type: "Retro-Leder", priceMin: 50, priceMax: 60, reason: "", image: "/gear/five-oklahoma.webp", amazon: "B09PJMWXQR" },
      { name: "Held Springride Gore-Tex", type: "Langer Leder-Touring", priceMin: 120, priceMax: 140, reason: "", image: "/gear/held-springride-gore-tex.webp", amazon: "B0BS9M2C3K" },
    ],
    boots: [
      { name: "H-D Scout Boot",             type: "Urban Motorradboot", priceMin: 130,  priceMax: 150, reason: "Leder, Harley-Stil, alltagstauglich", image: "/gear/h-d-scout-boot.webp", amazon: "B004RDV5PK" },
      { name: "H-D Electron Stiefel",         type: "Cruiser-Boot",       priceMin: 100, priceMax: 200, reason: "Knöchelschutz im Harley-Stil" , url: "https://www.amazon.de/dp/B00B85P9RK", image: "/gear/h-d-leder-stiefel.webp", },
      { name: "Belstaff Trialmaster",      type: "Heritage Boot",      priceMin: 200, priceMax: 400, reason: "Zeitloses Design, Knöchelschutz" , url: "https://www.fc-moto.com/de-de/p/belstaff-trialmaster-motorrad-stiefel-braun-40-BST-105088BROWN40", image: "/gear/trialmaster-belstaff.webp", amazon: "B0G2CWMFW1" },
      { name: "TCX Blend 2 WP", type: "Heritage-Leder", priceMin: 160, priceMax: 200, reason: "", image: "/gear/tcx-blend-2-wp.webp", amazon: "B0GYFYCYKX" },
      { name: "Stylmartin Rocket", type: "Cruiser-Stiefel", priceMin: 200, priceMax: 240, reason: "", image: "/gear/stylmartin-rocket.webp", amazon: "B01BFBCQMC" },
      { name: "Daytona Journey GTX", type: "Touring Gore-Tex", priceMin: 280, priceMax: 350, reason: "", image: "/gear/daytona-journey-gtx.webp", amazon: "B004UAI6A2" },
      { name: "Stylmartin Sunset", type: "Heritage-Stiefel", priceMin: 120, priceMax: 140, reason: "", image: "/gear/stylmartin-sunset.webp", amazon: "B013WQNGTA" },
      { name: "Held Brickland LC GTX", type: "Heritage-Schnürstiefel", priceMin: 170, priceMax: 210, reason: "", image: "/gear/held-brickland-lc-gtx.webp", amazon: "B09PK19J6X" },
      { name: "IXS 2-Zip-SYM 2.0", type: "Tourenstiefel wasserdicht", priceMin: 80, priceMax: 90, reason: "", image: "/gear/ixs-2-zip-sym-2-0.webp", amazon: "B09V6L4NVR" },
    ],
    pants: [
      { name: "Büse Ferno",          type: "Textilhose",      priceMin: 80,  priceMax: 150, reason: "Alltagsoptik, CE-Level 1" , url: "https://www.amazon.de/dp/B081FD86H9", image: "/gear/buese-ferno-jeans.webp", },
      { name: "H-D Damen Leder-Chaps",          type: "Leder Chaps",        priceMin: 60, priceMax: 90, reason: "Klassischer Cruiser-Look", url: "https://shop.motorrad-matthies.com/products/leder-chaps-schwarz-98026-12vw", image: "/gear/h-d-damen-leder-chaps.webp" },
      { name: "Helstons Cargo Pants",      type: "Lederhose Retro",    priceMin: 250, priceMax: 420, reason: "Vintage-Stil, CE-Level 2" , url: "https://www.fc-moto.com/de-de/p/helstons-cargo-motorrad-textilhose-grau-28-HT-2021026-GR-28-US", image: "/gear/helstons-cargo-pants.webp", },
      { name: "John Doe Chester", type: "Motorradjeans", priceMin: 150, priceMax: 180, reason: "", image: "/gear/john-doe-chester.webp", amazon: "B0F32S9H12" },
      { name: "Spidi Superstorm H2Out", type: "Regenhose", priceMin: 120, priceMax: 140, reason: "", image: "/gear/spidi-superstorm-h2out.webp", amazon: "B007K5A6PM" },
      { name: "Alpinestars Hurricane V2", type: "Regen-Überhose", priceMin: 50, priceMax: 60, reason: "", image: "/gear/alpinestars-hurricane-v2.webp", amazon: "B0DW7R1R91" },
      { name: "Richa Rain Warrior", type: "Regen-Überhose", priceMin: 40, priceMax: 50, reason: "", image: "/gear/richa-rain-warrior.webp", amazon: "B0041GIK2O" },
    ],
    ...universalGear,
  },
  Enduro: {
    helmet: [
      { name: "O'Neal 3SRS",               type: "Offroad-Helm",       priceMin: 80,  priceMax: 150, reason: "Leicht, gute Belüftung, Einstieg" , url: "https://www.fc-moto.com/de-de/p/oneal-3srs-motocross-helm-blau-neon-gelb-xs-53-54-ONL-0625-051", image: "/gear/oneal-3srs.webp", amazon: "B0CC9B8XPG" },
      { name: "Fox V1",    type: "Offroad-Helm",       priceMin: 130, priceMax: 160, reason: "Leichter MX-Helm, gute Belüftung", image: "/gear/fox-v1.webp", amazon: "B0BQZC7QGQ" },
      { name: "Airoh Commander 2",         type: "Enduro-Helm",        priceMin: 300, priceMax: 480, reason: "Carbon, ultraleicht, dual-sport" , url: "https://www.louis.de/artikel/airoh-commander-2-endurohelm/213891", image: "/gear/airoh-commander-2.webp", amazon: "B0CSLP34BQ" },
      { name: "Nolan N100-6", type: "Klapphelm", priceMin: 240, priceMax: 300, reason: "", image: "/gear/nolan-n100-6.webp", amazon: "B0DJR9698M" },
      { name: "HJC i50", type: "Crosshelm", priceMin: 140, priceMax: 170, reason: "", image: "/gear/hjc-i50.webp", amazon: "B07YQ524HR" },
      { name: "Arai Tour-X5", type: "Adventurehelm", priceMin: 400, priceMax: 490, reason: "", image: "/gear/arai-tour-x5.webp", amazon: "B0DLX6NXR6" },
      { name: "Caberg Horus X", type: "Klapphelm", priceMin: 200, priceMax: 240, reason: "", amazon: "B0C33ZDKW9", image: "/gear/caberg-horus-x.webp" },
      { name: "LS2 Advant X Carbon", type: "Klapphelm 180°", priceMin: 300, priceMax: 360, reason: "", amazon: "B0BRQ8774H", image: "/gear/ls2-advant-x-carbon.webp" },
    ],
    jacket: [
      { name: "Fox Flexair Jersey",        type: "MX Trikot",          priceMin: 50,  priceMax: 120, reason: "Leicht, atmungsaktiv, kombinierbar" , url: "https://www.louis.de/artikel/fox-flexair-infinite-mx-jersey/213550", image: "/gear/fox-flexair-jersey.webp", amazon: "B09PSVQ54G" },
      { name: "Alpinestars Andes v3",      type: "Touring-Jacket",     priceMin: 100, priceMax: 300, reason: "Wasserdicht, Protektoren inklusive" , url: "https://www.fc-moto.com/en-en/p/alpinestars-andes-v3-camo-drystar-motorcycle-textile-jacket-s-APS-3207521-858-S", image: "/gear/alpinestars-andes-v3.webp", amazon: "B0BPK2K6TP" },
      { name: "Klim Badlands Pro",         type: "Adventure-Jacket",   priceMin: 400, priceMax: 650, reason: "Gore-Tex, maximaler Schutz" , url: "https://www.fc-moto.com/de-de/p/klim-badlands-pro-2023-motorrad-textiljacke-schwarz-s-KLM-4052-003-120-001", image: "/gear/klim-badlands-pro.webp", },
      { name: "Rev'it Tornado 4 H2O Jacke", type: "Adventure-Textiljacke", priceMin: 290, priceMax: 350, reason: "", image: "/gear/rev-it-tornado-4-h2o-jacke.webp", amazon: "B0CWDHJ624" },
      { name: "Held Tourino Top", type: "Touring-Textiljacke", priceMin: 130, priceMax: 160, reason: "", image: "/gear/held-tourino-top.webp", amazon: "B09QHHHVWT" },
      { name: "Spidi 4 Season V3 H2Out", type: "Touring-Textiljacke", priceMin: 410, priceMax: 500, reason: "", image: "/gear/spidi-4-season-v3-h2out.webp", amazon: "B0FC8LKGL2" },
      { name: "Furygan Apalaches Evo", type: "Adventure-Textiljacke", priceMin: 220, priceMax: 270, reason: "", image: "/gear/furygan-apalaches-evo.webp", amazon: "B0DSQ92MG6" },
      { name: "Fox 360 Vizen Jersey", type: "MX-Jersey", priceMin: 50, priceMax: 60, reason: "", image: "/gear/fox-360-vizen-jersey.webp", amazon: "B09PSM1NYP" },
      { name: "Büse Lago III", type: "Textil-Tourenjacke", priceMin: 170, priceMax: 210, reason: "", image: "/gear/buse-lago-iii.webp", amazon: "B0GHNTXKTK" },
      { name: "Büse Lago III Damen", type: "Damen-Textiljacke", priceMin: 170, priceMax: 200, reason: "", image: "/gear/buse-lago-iii-damen.webp", amazon: "B0GHNK341Y" },
      { name: "Alpinestars Halo Drystar", type: "Adventure-Textiljacke", priceMin: 340, priceMax: 410, reason: "", image: "/gear/alpinestars-halo-drystar.webp", amazon: "B09WXSW23X" },
      { name: "Alpinestars Stella Andes V4", type: "Damen-Tourenjacke", priceMin: 240, priceMax: 300, reason: "", image: "/gear/alpinestars-stella-andes-v4.webp", amazon: "B0FR3RQG5G" },
      { name: "Rev'it Offtrack 2 H2O", type: "Adventure-Textiljacke", priceMin: 250, priceMax: 310, reason: "", image: "/gear/rev-it-offtrack-2-h2o.webp", amazon: "B0BSLL115T" },
      { name: "Held Zorro ST Top", type: "Allwetter-Textiljacke", priceMin: 180, priceMax: 220, reason: "", image: "/gear/held-zorro-st-top.webp", amazon: "B0FTZJDD39" },
      { name: "Oxford Rainseal", type: "Regenüberjacke", priceMin: 50, priceMax: 60, reason: "", image: "/gear/oxford-rainseal.webp", amazon: "B0BL1HB5YQ" },
      { name: "Leatt Moto 4.5 X-Flow", type: "MX-Mesh-Jacke", priceMin: 120, priceMax: 150, reason: "", image: "/gear/leatt-moto-4-5-x-flow.webp", amazon: "B0BCRWYWV1" },
      { name: "Leatt Moto 4.5 HydraDri", type: "Enduro-Regenjacke", priceMin: 130, priceMax: 160, reason: "", image: "/gear/leatt-moto-4-5-hydradri.webp", amazon: "B0CC92S3SV" },
    ],
    gloves: [
      { name: "Fox Dirtpaw",               type: "MX Handschuhe",      priceMin: 20,  priceMax: 50,  reason: "Griffig, strapazierfähig, günstig" , url: "https://www.louis.de/artikel/fox-dirtpaw-mx-handschuhe/210705", image: "/gear/fox-dirtpaw.webp", amazon: "B0BQXBHCBL" },
      { name: "Alpinestars Dune",       type: "Offroad-Handschuhe", priceMin: 50,  priceMax: 90,  reason: "Guter Schutz, atmungsaktiv", url: "https://www.enduro4you.de/p/alpinestars-dune-handschuhe-navy-white-cyan", image: "/gear/alpinestars-dune.webp" },
      { name: "Held Sambia 2",             type: "Touring-Handschuhe", priceMin: 80,  priceMax: 140, reason: "WP-Membran, CE-Level 2" , url: "https://www.louis.de/artikel/held-22569-sambia-2-handschuhe/210953", image: "/gear/held-sambia-2.webp", amazon: "B0DZJZRPPX" },
      { name: "Dainese Teyde Gore-Tex", type: "Winter-Touring, wasserdicht", priceMin: 100, priceMax: 120, reason: "", image: "/gear/dainese-teyde-gore-tex.webp", amazon: "B0DPHSBGZD" },
      { name: "Rev'it Mangrove 2", type: "Adventure-Sommer", priceMin: 60, priceMax: 70, reason: "", image: "/gear/rev-it-mangrove-2.webp", amazon: "B0GRCP71S6" },
      { name: "IXS Arctic-GTX 2.0", type: "Winter Gore-Tex", priceMin: 70, priceMax: 90, reason: "", image: "/gear/ixs-arctic-gtx-2-0.webp", amazon: "B08NFQ3BF9" },
      { name: "Büse Brandon", type: "Touring, wasserdicht", priceMin: 50, priceMax: 70, reason: "", image: "/gear/buse-brandon.webp", amazon: "B0CCL9LF69" },
      { name: "Dainese Tempest 2 D-Dry", type: "Touring wasserdicht", priceMin: 90, priceMax: 110, reason: "", image: "/gear/dainese-tempest-2-d-dry.webp", amazon: "B0CJ768NHY" },
      { name: "Spidi Wintertourer-KP", type: "Winterhandschuh", priceMin: 70, priceMax: 80, reason: "", image: "/gear/spidi-wintertourer-kp.webp", amazon: "B0DTMQFHHF" },
      { name: "Furygan Yakuru D3O WP", type: "Allwetter wasserdicht", priceMin: 60, priceMax: 70, reason: "", image: "/gear/furygan-yakuru-d3o-wp.webp", amazon: "B0BXDJTTGZ" },
      { name: "Leatt 2.5 X-Flow", type: "MX-Handschuh", priceMin: 20, priceMax: 20, reason: "", image: "/gear/leatt-2-5-x-flow.webp", amazon: "B0BCSBVKVL" },
    ],
    boots: [
      { name: "TCX Comp Evo 2",            type: "Offroad-Stiefel",    priceMin: 100, priceMax: 250, reason: "Solider Schutz, gute Passform" , url: "https://www.fc-moto.com/de-de/p/tcx-comp-evo-2-michelin-motocross-stiefel-blau-rot-38-TCX-9662-RBBY-38", image: "/gear/tcx-comp-evo-2.webp", amazon: "B08N1KZS3S" },
      { name: "Alpinestars Tech 7 Enduro", type: "Enduro-Stiefel",     priceMin: 200, priceMax: 440, reason: "Wasserdicht, Knöchelschutz, Grip" , url: "https://www.louis.de/artikel/alpinestars-tech-7-enduro-ds-stiefel/31952001", image: "/gear/alpinestars-tech-7-enduro.webp", amazon: "B0FFHQC95H" },
      { name: "Sidi Crossfire 3 SRS",      type: "MX Premium-Stiefel", priceMin: 350, priceMax: 500, reason: "Maximaler Schutz, Präzisionspassform" , url: "https://www.louis.de/artikel/sidi-crossfire-3-srs-motocross-stiefel/219514", image: "/gear/sidi-crossfire-3-srs.webp", amazon: "B08487MBWG" },
      { name: "TCX Clima 2 Surround GTX", type: "Touring Gore-Tex", priceMin: 240, priceMax: 290, reason: "", image: "/gear/tcx-clima-2-surround-gtx.webp", amazon: "B0BXSLWZBZ" },
      { name: "TCX Explorer.4 GTX", type: "Adventure-Stiefel", priceMin: 200, priceMax: 240, reason: "", image: "/gear/tcx-explorer-4-gtx.webp", amazon: "B0GYFNZKNN" },
      { name: "Forma Terra Evo Low WP", type: "Kurzer Adventure-Stiefel", priceMin: 250, priceMax: 310, reason: "", image: "/gear/forma-terra-evo-low-wp.webp", amazon: "B07ZTK3KRD" },
      { name: "Daytona Journey GTX", type: "Touring Gore-Tex", priceMin: 280, priceMax: 350, reason: "", image: "/gear/daytona-journey-gtx.webp", amazon: "B004UAI6A2" },
      { name: "Gaerne SG 12", type: "MX-Stiefel", priceMin: 390, priceMax: 470, reason: "", image: "/gear/gaerne-sg-12.webp", amazon: "B0D64CBNYQ" },
      { name: "Alpinestars Tech 3 Enduro", type: "Enduro-Stiefel", priceMin: 210, priceMax: 250, reason: "", image: "/gear/alpinestars-tech-3-enduro.webp", amazon: "B074QN1MGK" },
      { name: "Forma Adventure Low", type: "Adventure-Halbstiefel", priceMin: 220, priceMax: 270, reason: "", image: "/gear/forma-adventure-low.webp", amazon: "B01DW4SH14" },
    ],
    pants: [
      { name: "Fox Defend Pant",           type: "MTB/Enduro Hose",    priceMin: 80,  priceMax: 170, reason: "Bewegungsfreiheit, robust" , url: "https://www.fc-moto.com/en-en/p/fox-defend-bicycle-pants-olive-28-FOX-32372-099-28", image: "/gear/fox-defend-pant.webp", amazon: "B0CQMKH3X6" },
      { name: "Alpinestars Andes v3 Pant", type: "Adventure Hose",     priceMin: 110, priceMax: 320, reason: "Wasserdicht, CE-Level 2" , url: "https://www.fc-moto.com/en-en/p/alpinestars-andes-v3-drystar-motorcycle-textile-pants-black-m-APS-3227521-10-M", image: "/gear/alpinestars-andes-v3-pant.webp", amazon: "B08HPC8M47" },
      { name: "Klim Badlands Pro Pant",    type: "Adventure Hose",     priceMin: 350, priceMax: 550, reason: "Gore-Tex, maximaler Schutz" , url: "https://www.fc-moto.com/de-de/p/klim-badlands-pro-2023-motorrad-textilhose-braun-sand-32-KLM-4053-003-032-904", image: "/gear/klim-badlands-pro-pant.webp", },
      { name: "Held Lonborg Base", type: "Adventure-Textilhose", priceMin: 270, priceMax: 330, reason: "", image: "/gear/held-lonborg-base.webp", amazon: "B0DWY1KRCH" },
      { name: "IXS Shape-ST", type: "Touring-Textilhose", priceMin: 150, priceMax: 180, reason: "", image: "/gear/ixs-shape-st.webp", amazon: "B0847QZHJF" },
      { name: "Spidi Superstorm H2Out", type: "Regenhose", priceMin: 120, priceMax: 140, reason: "", image: "/gear/spidi-superstorm-h2out.webp", amazon: "B007K5A6PM" },
      { name: "Alpinestars Hurricane V2", type: "Regen-Überhose", priceMin: 50, priceMax: 60, reason: "", image: "/gear/alpinestars-hurricane-v2.webp", amazon: "B0DW7R1R91" },
      { name: "Dainese Tempest 4 D-Dry", type: "Tourenhose wasserdicht", priceMin: 220, priceMax: 270, reason: "", image: "/gear/dainese-tempest-4-d-dry.webp", amazon: "B0HF8FTQRF" },
      { name: "Dainese Storm 2", type: "Regen-Überhose", priceMin: 90, priceMax: 100, reason: "", image: "/gear/dainese-storm-2.webp", amazon: "B08L3FC3NK" },
      { name: "Richa Rain Warrior", type: "Regen-Überhose", priceMin: 40, priceMax: 50, reason: "", image: "/gear/richa-rain-warrior.webp", amazon: "B0041GIK2O" },
      { name: "Furygan Apalaches Vented", type: "Adventure-Hose", priceMin: 100, priceMax: 120, reason: "", image: "/gear/furygan-apalaches-vented.webp", amazon: "B0B6T3HBL3" },
      { name: "Leatt ADV FlowTour 5.5", type: "Adventure-Hose", priceMin: 210, priceMax: 260, reason: "", image: "/gear/leatt-adv-flowtour-5-5.webp", amazon: "B0DT4Q1P25" },
      { name: "Leatt Moto 4.5", type: "MX-Hose", priceMin: 80, priceMax: 90, reason: "", image: "/gear/leatt-moto-4-5.webp", amazon: "B092DVH9JJ" },
    ],
    ...universalGear,
  },
  Motocross: {
    helmet: [
      { name: "O'Neal 3SRS MX",            type: "MX Helm",            priceMin: 70,  priceMax: 150, reason: "Einstieg, leicht, ventiliert" , url: "https://www.fc-moto.com/de-de/p/oneal-3srs-vision-motocross-helm-schwarz-grau-xs-53-54-ONL-0625-291", image: "/gear/oneal-3srs-mx.webp", amazon: "B095WCJ3SM" },
      { name: "Fox V1",    type: "MX Helm",            priceMin: 130, priceMax: 160, reason: "Leichter MX-Helm, gute Belüftung", image: "/gear/fox-v1.webp", amazon: "B0BQZC7QGQ" },
      { name: "Bell Moto-10",              type: "MX Premium-Helm",    priceMin: 450, priceMax: 930, reason: "MIPS, maximale Sicherheit" , url: "https://www.fc-moto.com/en-en/p/bell-moto-10-mips-motocross-helmet-black-matt-s-55-56-BEL-37008-255-S", image: "/gear/bell-moto-10.webp", amazon: "B0BZJLKL8C" },
      { name: "HJC i50", type: "Crosshelm", priceMin: 140, priceMax: 170, reason: "", image: "/gear/hjc-i50.webp", amazon: "B07YQ524HR" },
    ],
    jacket: [
      { name: "Fly Racing Kinetic",        type: "MX Jersey",          priceMin: 40,  priceMax: 80,  reason: "Günstig, leicht, atmungsaktiv" , url: "https://www.fc-moto.com/en-en/p/fly-racing-kinetic-fuel-motocross-jersey-black-m-FLY-70201-M-420", image: "/gear/fly-racing-kinetic.webp", amazon: "B0D9CBMXNS" },
      { name: "Fox 180 Jersey",             type: "MX Jersey",   priceMin: 40, priceMax: 40, reason: "Leicht, atmungsaktiv (Hose separat)", image: "/gear/fox-180-jersey.webp", amazon: "B0BQXDMVWG" },
      { name: "Alpinestars Techstar",      type: "MX Race-Set",        priceMin: 200, priceMax: 350, reason: "Profi-Level, optimale Passform" , url: "https://www.louis.de/artikel/alpinestars-techstar-arch-mx-jersey/212980", image: "/gear/alpinestars-techstar.webp", },
      { name: "Fox 360 Vizen Jersey", type: "MX-Jersey", priceMin: 50, priceMax: 60, reason: "", image: "/gear/fox-360-vizen-jersey.webp", amazon: "B09PSM1NYP" },
      { name: "Leatt Moto 4.5 X-Flow", type: "MX-Mesh-Jacke", priceMin: 120, priceMax: 150, reason: "", image: "/gear/leatt-moto-4-5-x-flow.webp", amazon: "B0BCRWYWV1" },
      { name: "Leatt Moto 4.5 HydraDri", type: "Enduro-Regenjacke", priceMin: 130, priceMax: 160, reason: "", image: "/gear/leatt-moto-4-5-hydradri.webp", amazon: "B0CC92S3SV" },
    ],
    gloves: [
      { name: "Fox Dirtpaw Race",          type: "MX Handschuhe",      priceMin: 20,  priceMax: 40,  reason: "Klassiker im Motocross", image: "/gear/fox-dirtpaw-race.webp", amazon: "B0BQXBHCBL" },
      { name: "Alpinestars Radar",         type: "MX Handschuhe",      priceMin: 30,  priceMax: 70,  reason: "Guter Schutz, Grip" , url: "https://www.louis.de/artikel/alpinestars-radar-mx-handschuhe/210821", image: "/gear/alpinestars-radar.webp", amazon: "B0CCKKX87Y" },
      { name: "Held Backflip",               type: "MX Handschuhe",      priceMin: 55,  priceMax: 75, reason: "CE-Level 2, Premium-Verarbeitung", url: "https://www.cs-bikewear.de/held-backflip-moto-cross-handschuh-246300.34", image: "/gear/held-backflip.webp" },
      { name: "Leatt 2.5 X-Flow", type: "MX-Handschuh", priceMin: 20, priceMax: 20, reason: "", image: "/gear/leatt-2-5-x-flow.webp", amazon: "B0BCSBVKVL" },
    ],
    boots: [
      { name: "TCX Comp Evo 2",            type: "MX Stiefel",         priceMin: 100, priceMax: 250, reason: "Solider Schutz, leicht" , url: "https://www.fc-moto.com/de-de/p/tcx-comp-evo-2-michelin-motocross-stiefel-blau-rot-38-TCX-9662-RBBY-38", image: "/gear/tcx-comp-evo-2.webp", amazon: "B08N1KZS3S" },
      { name: "Sidi Crossfire 3",          type: "MX Premium-Stiefel", priceMin: 300, priceMax: 500, reason: "Präzisionspassform, top Schutz" , url: "https://www.louis.de/artikel/sidi-crossfire-3-motocross-stiefel/219518", image: "/gear/sidi-crossfire-3.webp", amazon: "B07JDH9WC4" },
      { name: "Alpinestars Tech 10",       type: "MX Stiefel",         priceMin: 400, priceMax: 680, reason: "Maximaler Knöchelschutz" , url: "https://www.louis.de/artikel/alpinestars-tech-10-motocross-stiefel/501360", image: "/gear/alpinestars-tech-10.webp", amazon: "B07FTBWD62" },
      { name: "Gaerne SG 12", type: "MX-Stiefel", priceMin: 390, priceMax: 470, reason: "", image: "/gear/gaerne-sg-12.webp", amazon: "B0D64CBNYQ" },
      { name: "Alpinestars Tech 3 Enduro", type: "Enduro-Stiefel", priceMin: 210, priceMax: 250, reason: "", image: "/gear/alpinestars-tech-3-enduro.webp", amazon: "B074QN1MGK" },
    ],
    pants: [
      { name: "O'Neal Element Racewear",   type: "MX Race Hose",       priceMin: 50,  priceMax: 100, reason: "Einstieg, leicht, haltbar" , url: "https://www.louis.de/artikel/o-neal-element-racewear-crosshose/211874", image: "/gear/oneal-element-racewear.webp", amazon: "B0FFRMZMKJ" },
      { name: "Fox 180 MX Hose",           type: "MX Hose",            priceMin: 60,  priceMax: 140, reason: "Leicht, robust, Bewegungsfreiheit" , url: "https://www.louis.de/artikel/fox-180-bnkr-crosshose/211642", image: "/gear/fox-180-mx-hose.webp", amazon: "B0CQ6YWW3P" },
      { name: "Alpinestars Racer MX Pant", type: "MX Hose",            priceMin: 90, priceMax: 180, reason: "CE-Knieprotektoren, atmungsaktiv" , url: "https://www.louis.de/artikel/alpinestars-racer-graphite-crosshose/211754", image: "/gear/alpinestars-racer-mx-pant.webp", amazon: "B0BBKGH6GW" },
      { name: "Leatt Moto 4.5", type: "MX-Hose", priceMin: 80, priceMax: 90, reason: "", image: "/gear/leatt-moto-4-5.webp", amazon: "B092DVH9JJ" },
    ],
    ...universalGear,
  },
  Klassiker: {
    helmet: [
      { name: "Biltwell Lane Splitter",         type: "Integral Vintage",   priceMin: 310, priceMax: 380, reason: "Custom-Look, kompakte Schale", image: "/gear/biltwell-lane-splitter.webp", amazon: "B06Y28Y3N3" },
      { name: "Hedon Heroine Racer",       type: "Integral Vintage",   priceMin: 850, priceMax: 950, reason: "Handgefertigt, Vintage-Optik, ECE", url: "https://www.24helmets.de/hedon-heroine-racer-2.0-signature-black-ece", image: "/gear/hedon-heroine-racer.webp" },
      { name: "Davida Speedster v4",         type: "Jethelm Klassisch",  priceMin: 350, priceMax: 450, reason: "Britisches Handwerk, zeitlos", url: "https://www.24helmets.de/davida-speedster-v4-schwarz-ece/112021.2m", image: "/gear/davida-speedster-v4.webp" },
      { name: "LS2 Copter II", type: "Jethelm", priceMin: 100, priceMax: 120, reason: "", image: "/gear/ls2-copter-ii.webp", amazon: "B0C6R1P874" },
      { name: "Nolan N80-8", type: "Integralhelm", priceMin: 190, priceMax: 230, reason: "", amazon: "B0DK24JGBJ", image: "/gear/nolan-n80-8.webp" },
      { name: "Bell Custom 500", type: "Retro-Jethelm", priceMin: 180, priceMax: 220, reason: "", amazon: "B0DFCH3SFY", image: "/gear/bell-custom-500.webp" },
    ],
    jacket: [
      { name: "Helstons Tracker",         type: "Lederjacke Retro",   priceMin: 330, priceMax: 400, reason: "Vintage-Leder, klassischer Schnitt", image: "/gear/helstons-tracker.webp", amazon: "B08BZWJGLH" },
      { name: "Belstaff Trackmaster",       type: "Gewachste Baumwolle", priceMin: 540, priceMax: 660, reason: "Wasserdicht gewachst, Heritage-Klassiker", image: "/gear/belstaff-trackmaster.webp", amazon: "B0F6MC8P5W" },
      { name: "Lewis Leathers Corsair",    type: "Café Racer Leder",   priceMin: 1400, priceMax: 1800, reason: "Britisches Heritage, CE zertifiziert", url: "https://www.lewisleathers.com/products/the-corsair-no-60", image: "/gear/lewis-leathers-corsair.webp" },
      { name: "Macna Tryton NightEye", type: "Leder-/Textiljacke", priceMin: 310, priceMax: 370, reason: "", image: "/gear/macna-tryton-nighteye.webp", amazon: "B0F14RDHDV" },
      { name: "Furygan Clint Evo", type: "Retro-Lederjacke", priceMin: 250, priceMax: 310, reason: "", image: "/gear/furygan-clint-evo.webp", amazon: "B0B6PXT178" },
      { name: "Büse Lago III", type: "Textil-Tourenjacke", priceMin: 170, priceMax: 210, reason: "", image: "/gear/buse-lago-iii.webp", amazon: "B0GHNTXKTK" },
      { name: "Büse Lago III Damen", type: "Damen-Textiljacke", priceMin: 170, priceMax: 200, reason: "", image: "/gear/buse-lago-iii-damen.webp", amazon: "B0GHNK341Y" },
      { name: "Büse Livorno", type: "Sommer-Meshjacke", priceMin: 140, priceMax: 180, reason: "", image: "/gear/buse-livorno.webp", amazon: "B0C53KYF2Y" },
      { name: "Alpinestars Stella Andes V4", type: "Damen-Tourenjacke", priceMin: 240, priceMax: 300, reason: "", image: "/gear/alpinestars-stella-andes-v4.webp", amazon: "B0FR3RQG5G" },
      { name: "Held Zorro ST Top", type: "Allwetter-Textiljacke", priceMin: 180, priceMax: 220, reason: "", image: "/gear/held-zorro-st-top.webp", amazon: "B0FTZJDD39" },
      { name: "Richa Infinity 2 Damen", type: "Damen-Textiljacke", priceMin: 150, priceMax: 190, reason: "", image: "/gear/richa-infinity-2-damen.webp", amazon: "B0883FDFYQ" },
      { name: "Modeka Clarke", type: "Textil-Tourenjacke", priceMin: 90, priceMax: 110, reason: "", image: "/gear/modeka-clarke.webp", amazon: "B07J6JKDTM" },
      { name: "Oxford Rainseal", type: "Regenüberjacke", priceMin: 50, priceMax: 60, reason: "", image: "/gear/oxford-rainseal.webp", amazon: "B0BL1HB5YQ" },
      { name: "IXS Classic SO 2.0", type: "Retro-Textiljacke", priceMin: 180, priceMax: 220, reason: "", image: "/gear/ixs-classic-so-2-0.webp", amazon: "B0C5RWJPM8" },
    ],
    gloves: [
      { name: "Biltwell Moto",             type: "Kurzhandschuh Synthetik", priceMin: 30, priceMax: 60,  reason: "Klassisch, günstig", url: "https://shop.thunderbike.de/Bekleidung/Herren/Handschuhe/Biltwell-Moto-Gloves-Handschuhe-schwarz.html", image: "/gear/biltwell-moto.webp" },
      { name: "Held Classic",              type: "Premium Leder",      priceMin: 50,  priceMax: 150, reason: "Handgefertigt, Vintage-Passform" , url: "https://www.fc-moto.com/de-de/p/held-classic-rider-motorradhandschuhe-gelb-7-HE-022003-00-57-7", image: "/gear/held-classic.webp", amazon: "B07ZC15Z55" },
      { name: "Dainese Teyde Gore-Tex", type: "Winter-Touring, wasserdicht", priceMin: 100, priceMax: 120, reason: "", image: "/gear/dainese-teyde-gore-tex.webp", amazon: "B0DPHSBGZD" },
      { name: "Rev'it Access", type: "Urban-Sommer", priceMin: 30, priceMax: 40, reason: "", image: "/gear/rev-it-access.webp", amazon: "B0CZSDGH3F" },
      { name: "Büse Miles", type: "Retro-Leder perforiert", priceMin: 60, priceMax: 80, reason: "", image: "/gear/buse-miles.webp", amazon: "B0CCL7N1ZL" },
      { name: "Dainese Mig 3", type: "Kurzer Lederhandschuh", priceMin: 40, priceMax: 50, reason: "", image: "/gear/dainese-mig-3.webp", amazon: "B0CMJHSN8R" },
      { name: "Alpinestars Stella Copper", type: "Damen-Sommer", priceMin: 40, priceMax: 50, reason: "", image: "/gear/alpinestars-stella-copper.webp", amazon: "B07TWNV8FX" },
      { name: "Five Oklahoma", type: "Retro-Leder", priceMin: 50, priceMax: 60, reason: "", image: "/gear/five-oklahoma.webp", amazon: "B09PJMWXQR" },
      { name: "Knox Orsa Leather MK3", type: "Leder mit Kahnbeinschutz", priceMin: 140, priceMax: 170, reason: "", image: "/gear/knox-orsa-leather-mk3.webp", amazon: "B0FCYQ9THG" },
      { name: "Held Springride Gore-Tex", type: "Langer Leder-Touring", priceMin: 120, priceMax: 140, reason: "", image: "/gear/held-springride-gore-tex.webp", amazon: "B0BS9M2C3K" },
    ],
    boots: [
      { name: "H-D Scout Boot",             type: "Urban Boot",         priceMin: 130,  priceMax: 150, reason: "Leder, Harley-Stil, alltagstauglich", image: "/gear/h-d-scout-boot.webp", amazon: "B004RDV5PK" },
      { name: "Belstaff Trialmaster",      type: "Heritage Boot",      priceMin: 200, priceMax: 400, reason: "Zeitloses Design, Knöchelschutz" , url: "https://www.fc-moto.com/de-de/p/belstaff-trialmaster-motorrad-stiefel-braun-40-BST-105088BROWN40", image: "/gear/trialmaster-belstaff.webp", amazon: "B0G2CWMFW1" },
      { name: "Wesco Boss",                type: "Heritage Stiefel",   priceMin: 800, priceMax: 1000, reason: "Amerikanisches Handwerk, ikonisch", url: "https://ironheartgermany.com/products/wesco-we-cxl7710705-blk-custom-boss-engineer-chromexcel-black", image: "/gear/wesco-boss.webp" },
      { name: "TCX Blend 2 WP", type: "Heritage-Leder", priceMin: 160, priceMax: 200, reason: "", image: "/gear/tcx-blend-2-wp.webp", amazon: "B0GYFYCYKX" },
      { name: "Stylmartin Atom", type: "Urban-Sneaker", priceMin: 160, priceMax: 190, reason: "", image: "/gear/stylmartin-atom.webp", amazon: "B072PW25HR" },
      { name: "Stylmartin Rocket", type: "Cruiser-Stiefel", priceMin: 200, priceMax: 240, reason: "", image: "/gear/stylmartin-rocket.webp", amazon: "B01BFBCQMC" },
      { name: "Rev'it Arrow 2 H2O", type: "Urban-Sneaker, wasserdicht", priceMin: 130, priceMax: 160, reason: "", image: "/gear/rev-it-arrow-2-h2o.webp", amazon: "B0GQ665BQN" },
      { name: "Dainese Dover Gore-Tex", type: "Urban-Schuh wasserdicht", priceMin: 300, priceMax: 360, reason: "", image: "/gear/dainese-dover-gore-tex.webp", amazon: "B07Y2L1R48" },
      { name: "Forma Adventure Low", type: "Adventure-Halbstiefel", priceMin: 220, priceMax: 270, reason: "", image: "/gear/forma-adventure-low.webp", amazon: "B01DW4SH14" },
      { name: "Gaerne G-Zion Gore-Tex", type: "Urban-Schuh wasserdicht", priceMin: 150, priceMax: 180, reason: "", image: "/gear/gaerne-g-zion-gore-tex.webp", amazon: "B0H4PD52KZ" },
      { name: "Gaerne G-Rome GTX", type: "Urban-Schuh wasserdicht", priceMin: 160, priceMax: 200, reason: "", image: "/gear/gaerne-g-rome-gtx.webp", amazon: "B0FFGF3JCN" },
      { name: "Stylmartin Sunset", type: "Heritage-Stiefel", priceMin: 120, priceMax: 140, reason: "", image: "/gear/stylmartin-sunset.webp", amazon: "B013WQNGTA" },
      { name: "Daytona Road Star GTX", type: "Tourenstiefel wasserdicht", priceMin: 360, priceMax: 440, reason: "", image: "/gear/daytona-road-star-gtx.webp", amazon: "B01BWM3984" },
      { name: "Held Brickland LC GTX", type: "Heritage-Schnürstiefel", priceMin: 170, priceMax: 210, reason: "", image: "/gear/held-brickland-lc-gtx.webp", amazon: "B09PK19J6X" },
      { name: "Falco Lennox 3", type: "Urban-Schuh", priceMin: 130, priceMax: 160, reason: "", image: "/gear/falco-lennox-3.webp", amazon: "B0FTZFX1BD" },
      { name: "IXS 2-Zip-SYM 2.0", type: "Tourenstiefel wasserdicht", priceMin: 80, priceMax: 90, reason: "", image: "/gear/ixs-2-zip-sym-2-0.webp", amazon: "B09V6L4NVR" },
    ],
    pants: [
      { name: "Büse Ferno",          type: "Textilhose",      priceMin: 80,  priceMax: 150, reason: "Alltagsoptik, CE-Level 1" , url: "https://www.amazon.de/dp/B081FD86H9", image: "/gear/buese-ferno-jeans.webp", },
      { name: "Helstons Corden Cargo",     type: "Textilhose Retro",    priceMin: 130, priceMax: 380, reason: "Vintage-Stil, CE-Protektoren" , url: "https://www.fc-moto.com/de-de/p/helstons-corden-armalith-motorrad-textilhose-khaki-30-HT-2021027-K-30-US", image: "/gear/helstons-corden-cargo.webp", amazon: "B09RF3VXYK" },
      { name: "Belstaff Snaefell",         type: "Heritage Hose",      priceMin: 260, priceMax: 320, reason: "Cordura-Motorradhose im Heritage-Stil", image: "/gear/belstaff-snaefell.webp", amazon: "B0855Y4VB7" },
      { name: "John Doe Chester", type: "Motorradjeans", priceMin: 150, priceMax: 180, reason: "", image: "/gear/john-doe-chester.webp", amazon: "B0F32S9H12" },
      { name: "Spidi Superstorm H2Out", type: "Regenhose", priceMin: 120, priceMax: 140, reason: "", image: "/gear/spidi-superstorm-h2out.webp", amazon: "B007K5A6PM" },
      { name: "Alpinestars Hurricane V2", type: "Regen-Überhose", priceMin: 50, priceMax: 60, reason: "", image: "/gear/alpinestars-hurricane-v2.webp", amazon: "B0DW7R1R91" },
      { name: "Shima Devon", type: "Motorradjeans Slim", priceMin: 90, priceMax: 110, reason: "", image: "/gear/shima-devon.webp", amazon: "B09WDMFWX1" },
      { name: "Bull-it Icona II", type: "Damen-Motorradjeans", priceMin: 120, priceMax: 140, reason: "", amazon: "B09QJL9BM6", image: "/gear/bull-it-icona-ii.webp" },
      { name: "Bering Trust Tapered", type: "Damen-Motorradjeans", priceMin: 100, priceMax: 120, reason: "", amazon: "B0FBS5GQ3X", image: "/gear/bering-trust-tapered.webp" },
      { name: "Macna Bombar Jeans", type: "Motorradjeans", priceMin: 110, priceMax: 140, reason: "", image: "/gear/macna-bombar-jeans.webp", amazon: "B0C74JKPHP" },
      { name: "Modeka Bratt", type: "Motorradjeans", priceMin: 140, priceMax: 180, reason: "", amazon: "B0F38CLS4F", image: "/gear/modeka-bratt.webp" },
      { name: "Furygan D12 X Kevlar", type: "Motorradjeans", priceMin: 150, priceMax: 190, reason: "", amazon: "B0FG7JJ9LY", image: "/gear/furygan-d12-x-kevlar.webp" },
    ],
    ...universalGear,
  },
  Custom: {
    helmet: [
      { name: "Biltwell Lane Splitter",         type: "Integral Custom",    priceMin: 310, priceMax: 380, reason: "Custom-Look, kompakte Schale", image: "/gear/biltwell-lane-splitter.webp", amazon: "B06Y28Y3N3" },
      { name: "Bell Bullitt",              type: "Retro-Integralhelm",     priceMin: 220, priceMax: 400, reason: "Klassischer Look, ECE 22.06" , url: "https://www.fc-moto.com/en-en/p/bell-bullitt-solid-helmet-black-matt-xs-54-55-BEL-8004720001", image: "/gear/bell-bullitt.webp", amazon: "B0FKN4VZ4H" },
      { name: "Hedon Heroine Racer",       type: "Integral Premium",   priceMin: 850, priceMax: 950, reason: "Handgefertigt, Unikat-Looks", url: "https://www.24helmets.de/hedon-heroine-racer-2.0-signature-black-ece", image: "/gear/hedon-heroine-racer.webp" },
      { name: "LS2 Copter II", type: "Jethelm", priceMin: 100, priceMax: 120, reason: "", image: "/gear/ls2-copter-ii.webp", amazon: "B0C6R1P874" },
      { name: "Bell Custom 500", type: "Retro-Jethelm", priceMin: 180, priceMax: 220, reason: "", amazon: "B0DFCH3SFY", image: "/gear/bell-custom-500.webp" },
    ],
    jacket: [
      { name: "Helstons Tracker",         type: "Lederjacke Retro",   priceMin: 330, priceMax: 400, reason: "Vintage-Leder, klassischer Schnitt", image: "/gear/helstons-tracker.webp", amazon: "B08BZWJGLH" },
      { name: "Deus Ex Machina Road Mesh",    type: "Mesh-Jacke Custom",       priceMin: 130, priceMax: 170, reason: "Cult-Brand, unique Aesthetik", url: "https://deuscustoms.eu/products/road-mesh-jacket-black", image: "/gear/deus-ex-machina-road-mesh.webp" },
      { name: "IXS Evo-Air", type: "Sommer-Mesh-Jacke", priceMin: 60, priceMax: 70, reason: "", image: "/gear/ixs-evo-air.webp", amazon: "B08NPHY8B1" },
      { name: "Furygan Clint Evo", type: "Retro-Lederjacke", priceMin: 250, priceMax: 310, reason: "", image: "/gear/furygan-clint-evo.webp", amazon: "B0B6PXT178" },
      { name: "Oxford Rainseal", type: "Regenüberjacke", priceMin: 50, priceMax: 60, reason: "", image: "/gear/oxford-rainseal.webp", amazon: "B0BL1HB5YQ" },
      { name: "IXS Classic SO 2.0", type: "Retro-Textiljacke", priceMin: 180, priceMax: 220, reason: "", image: "/gear/ixs-classic-so-2-0.webp", amazon: "B0C5RWJPM8" },
      { name: "Harley-Davidson Auroral 3in1", type: "Cruiser-Lederjacke", priceMin: 730, priceMax: 890, reason: "", image: "/gear/harley-davidson-auroral-3in1.webp", amazon: "B091H7DLS8" },
    ],
    gloves: [
      { name: "Biltwell Moto",             type: "Kurzhandschuh Synthetik", priceMin: 30, priceMax: 60,  reason: "Ikonisch, günstig, guter Grip", url: "https://shop.thunderbike.de/Bekleidung/Herren/Handschuhe/Biltwell-Moto-Gloves-Handschuhe-schwarz.html", image: "/gear/biltwell-moto.webp" },
      { name: "Held Classic",              type: "Premium Leder",      priceMin: 50,  priceMax: 150, reason: "Handgefertigt, elegantes Design" , url: "https://www.fc-moto.com/de-de/p/held-classic-rider-motorradhandschuhe-gelb-7-HE-022003-00-57-7", image: "/gear/held-classic.webp", amazon: "B07ZC15Z55" },
      { name: "Roland Sands Barfly",       type: "Custom Leder",       priceMin: 65,  priceMax: 90, reason: "Café-Racer Style, CE-Level 1", url: "https://monegroscycles.com/gb/roland-sands-design/445--roland-sands-design-barfly-black/", image: "/gear/roland-sands-barfly.webp" },
      { name: "Büse Miles", type: "Retro-Leder perforiert", priceMin: 60, priceMax: 80, reason: "", image: "/gear/buse-miles.webp", amazon: "B0CCL7N1ZL" },
      { name: "Dainese Mig 3", type: "Kurzer Lederhandschuh", priceMin: 40, priceMax: 50, reason: "", image: "/gear/dainese-mig-3.webp", amazon: "B0CMJHSN8R" },
      { name: "Alpinestars Stella Copper", type: "Damen-Sommer", priceMin: 40, priceMax: 50, reason: "", image: "/gear/alpinestars-stella-copper.webp", amazon: "B07TWNV8FX" },
      { name: "Five Oklahoma", type: "Retro-Leder", priceMin: 50, priceMax: 60, reason: "", image: "/gear/five-oklahoma.webp", amazon: "B09PJMWXQR" },
      { name: "Held Springride Gore-Tex", type: "Langer Leder-Touring", priceMin: 120, priceMax: 140, reason: "", image: "/gear/held-springride-gore-tex.webp", amazon: "B0BS9M2C3K" },
    ],
    boots: [
      { name: "H-D Scout Boot",             type: "Urban Motorradboot", priceMin: 130,  priceMax: 150, reason: "Leder, Harley-Stil, alltagstauglich", image: "/gear/h-d-scout-boot.webp", amazon: "B004RDV5PK" },
      { name: "Belstaff Trialmaster",      type: "Heritage Boot",      priceMin: 200, priceMax: 400, reason: "Zeitloses Design, Knöchelschutz" , url: "https://www.fc-moto.com/de-de/p/belstaff-trialmaster-motorrad-stiefel-braun-40-BST-105088BROWN40", image: "/gear/trialmaster-belstaff.webp", amazon: "B0G2CWMFW1" },
      { name: "Wesco Boss",                type: "Heritage Stiefel",   priceMin: 800, priceMax: 1000, reason: "Ikonisch, amerikanisches Handwerk", url: "https://ironheartgermany.com/products/wesco-we-cxl7710705-blk-custom-boss-engineer-chromexcel-black", image: "/gear/wesco-boss.webp" },
      { name: "TCX Blend 2 WP", type: "Heritage-Leder", priceMin: 160, priceMax: 200, reason: "", image: "/gear/tcx-blend-2-wp.webp", amazon: "B0GYFYCYKX" },
      { name: "Stylmartin Rocket", type: "Cruiser-Stiefel", priceMin: 200, priceMax: 240, reason: "", image: "/gear/stylmartin-rocket.webp", amazon: "B01BFBCQMC" },
      { name: "Gaerne G-Rome GTX", type: "Urban-Schuh wasserdicht", priceMin: 160, priceMax: 200, reason: "", image: "/gear/gaerne-g-rome-gtx.webp", amazon: "B0FFGF3JCN" },
      { name: "Stylmartin Sunset", type: "Heritage-Stiefel", priceMin: 120, priceMax: 140, reason: "", image: "/gear/stylmartin-sunset.webp", amazon: "B013WQNGTA" },
      { name: "Stylmartin Iron", type: "Urban-Sneaker", priceMin: 160, priceMax: 200, reason: "", image: "/gear/stylmartin-iron.webp", amazon: "B0727R486Y" },
      { name: "Held Brickland LC GTX", type: "Heritage-Schnürstiefel", priceMin: 170, priceMax: 210, reason: "", image: "/gear/held-brickland-lc-gtx.webp", amazon: "B09PK19J6X" },
    ],
    pants: [
      { name: "Büse Ferno",          type: "Textilhose",      priceMin: 80,  priceMax: 150, reason: "Alltagsoptik, CE-Level 1" , url: "https://www.amazon.de/dp/B081FD86H9", image: "/gear/buese-ferno-jeans.webp", },
      { name: "Helstons Corden Cargo",     type: "Textilhose Custom",   priceMin: 130, priceMax: 380, reason: "Vintage-Stil, CE-Protektoren" , url: "https://www.fc-moto.com/de-de/p/helstons-corden-armalith-motorrad-textilhose-khaki-30-HT-2021027-K-30-US", image: "/gear/helstons-corden-cargo.webp", amazon: "B09RF3VXYK" },
      { name: "John Doe Chester", type: "Motorradjeans", priceMin: 150, priceMax: 180, reason: "", image: "/gear/john-doe-chester.webp", amazon: "B0F32S9H12" },
      { name: "Spidi Superstorm H2Out", type: "Regenhose", priceMin: 120, priceMax: 140, reason: "", image: "/gear/spidi-superstorm-h2out.webp", amazon: "B007K5A6PM" },
      { name: "Alpinestars Hurricane V2", type: "Regen-Überhose", priceMin: 50, priceMax: 60, reason: "", image: "/gear/alpinestars-hurricane-v2.webp", amazon: "B0DW7R1R91" },
      { name: "Shima Devon", type: "Motorradjeans Slim", priceMin: 90, priceMax: 110, reason: "", image: "/gear/shima-devon.webp", amazon: "B09WDMFWX1" },
      { name: "Bull-it Icona II", type: "Damen-Motorradjeans", priceMin: 120, priceMax: 140, reason: "", amazon: "B09QJL9BM6", image: "/gear/bull-it-icona-ii.webp" },
      { name: "Macna Bombar Jeans", type: "Motorradjeans", priceMin: 110, priceMax: 140, reason: "", image: "/gear/macna-bombar-jeans.webp", amazon: "B0C74JKPHP" },
      { name: "Modeka Bratt", type: "Motorradjeans", priceMin: 140, priceMax: 180, reason: "", amazon: "B0F38CLS4F", image: "/gear/modeka-bratt.webp" },
      { name: "Furygan D12 X Kevlar", type: "Motorradjeans", priceMin: 150, priceMax: 190, reason: "", amazon: "B0FG7JJ9LY", image: "/gear/furygan-d12-x-kevlar.webp" },
    ],
    ...universalGear,
  },
}

const fallbackGear = gearByStyle.Naked

export function getGear(bikeStyle) {
  return gearByStyle[bikeStyle] || fallbackGear
}
